package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actafinal generated by hbm2java
 */
@Entity
@Table(name="actafinal"
    ,catalog="sgaundec"
)
public class Actafinal  implements java.io.Serializable {


     private Integer actaFinalId;
     private int llamadoId;
     private int materiaId;
     private Integer actaFinalLibro;
     private Integer actaFinalNumero;
     private Date actaFinalFecha;
     private String actaFinalHora;
     private Date actaFinalLimiteInscripcion;
     private Date actaFinalFechaCierre;
     private int presidenteId;
     private int vocalId;
     private int suplenteId;
     private String actaFinalObservaciones;
     private String actaFinalEstado;

    public Actafinal() {
    }

	
    public Actafinal(int llamadoId, int materiaId, int presidenteId, int vocalId, int suplenteId) {
        this.llamadoId = llamadoId;
        this.materiaId = materiaId;
        this.presidenteId = presidenteId;
        this.vocalId = vocalId;
        this.suplenteId = suplenteId;
    }
    public Actafinal(int llamadoId, int materiaId, Integer actaFinalLibro, Integer actaFinalNumero, Date actaFinalFecha, String actaFinalHora, Date actaFinalLimiteInscripcion, Date actaFinalFechaCierre, int presidenteId, int vocalId, int suplenteId, String actaFinalObservaciones, String actaFinalEstado) {
       this.llamadoId = llamadoId;
       this.materiaId = materiaId;
       this.actaFinalLibro = actaFinalLibro;
       this.actaFinalNumero = actaFinalNumero;
       this.actaFinalFecha = actaFinalFecha;
       this.actaFinalHora = actaFinalHora;
       this.actaFinalLimiteInscripcion = actaFinalLimiteInscripcion;
       this.actaFinalFechaCierre = actaFinalFechaCierre;
       this.presidenteId = presidenteId;
       this.vocalId = vocalId;
       this.suplenteId = suplenteId;
       this.actaFinalObservaciones = actaFinalObservaciones;
       this.actaFinalEstado = actaFinalEstado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="actaFinalId", unique=true, nullable=false)
    public Integer getActaFinalId() {
        return this.actaFinalId;
    }
    
    public void setActaFinalId(Integer actaFinalId) {
        this.actaFinalId = actaFinalId;
    }

    
    @Column(name="llamadoId", nullable=false)
    public int getLlamadoId() {
        return this.llamadoId;
    }
    
    public void setLlamadoId(int llamadoId) {
        this.llamadoId = llamadoId;
    }

    
    @Column(name="materiaId", nullable=false)
    public int getMateriaId() {
        return this.materiaId;
    }
    
    public void setMateriaId(int materiaId) {
        this.materiaId = materiaId;
    }

    
    @Column(name="actaFinalLibro")
    public Integer getActaFinalLibro() {
        return this.actaFinalLibro;
    }
    
    public void setActaFinalLibro(Integer actaFinalLibro) {
        this.actaFinalLibro = actaFinalLibro;
    }

    
    @Column(name="actaFinalNumero")
    public Integer getActaFinalNumero() {
        return this.actaFinalNumero;
    }
    
    public void setActaFinalNumero(Integer actaFinalNumero) {
        this.actaFinalNumero = actaFinalNumero;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="actaFinalFecha", length=10)
    public Date getActaFinalFecha() {
        return this.actaFinalFecha;
    }
    
    public void setActaFinalFecha(Date actaFinalFecha) {
        this.actaFinalFecha = actaFinalFecha;
    }

    
    @Column(name="actaFinalHora", length=10)
    public String getActaFinalHora() {
        return this.actaFinalHora;
    }
    
    public void setActaFinalHora(String actaFinalHora) {
        this.actaFinalHora = actaFinalHora;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="actaFinalLimiteInscripcion", length=10)
    public Date getActaFinalLimiteInscripcion() {
        return this.actaFinalLimiteInscripcion;
    }
    
    public void setActaFinalLimiteInscripcion(Date actaFinalLimiteInscripcion) {
        this.actaFinalLimiteInscripcion = actaFinalLimiteInscripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="actaFinalFechaCierre", length=10)
    public Date getActaFinalFechaCierre() {
        return this.actaFinalFechaCierre;
    }
    
    public void setActaFinalFechaCierre(Date actaFinalFechaCierre) {
        this.actaFinalFechaCierre = actaFinalFechaCierre;
    }

    
    @Column(name="presidenteId", nullable=false)
    public int getPresidenteId() {
        return this.presidenteId;
    }
    
    public void setPresidenteId(int presidenteId) {
        this.presidenteId = presidenteId;
    }

    
    @Column(name="VocalId", nullable=false)
    public int getVocalId() {
        return this.vocalId;
    }
    
    public void setVocalId(int vocalId) {
        this.vocalId = vocalId;
    }

    
    @Column(name="suplenteId", nullable=false)
    public int getSuplenteId() {
        return this.suplenteId;
    }
    
    public void setSuplenteId(int suplenteId) {
        this.suplenteId = suplenteId;
    }

    
    @Column(name="actaFinalObservaciones", length=150)
    public String getActaFinalObservaciones() {
        return this.actaFinalObservaciones;
    }
    
    public void setActaFinalObservaciones(String actaFinalObservaciones) {
        this.actaFinalObservaciones = actaFinalObservaciones;
    }

    
    @Column(name="actaFinalEstado", length=2)
    public String getActaFinalEstado() {
        return this.actaFinalEstado;
    }
    
    public void setActaFinalEstado(String actaFinalEstado) {
        this.actaFinalEstado = actaFinalEstado;
    }




}


