package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actaingreso generated by hbm2java
 */
@Entity
@Table(name="actaingreso"
    ,catalog="sgaundec"
)
public class Actaingreso  implements java.io.Serializable {


     private Integer actaIngresoId;
     private int periodoId;
     private int materiaId;
     private Date actaIngresoLimitePresentacion;
     private Date actaIngresoFecha;
     private String actaIngresoEstado;
     private String actaIngresoObservaciones;

    public Actaingreso() {
    }

	
    public Actaingreso(int periodoId, int materiaId) {
        this.periodoId = periodoId;
        this.materiaId = materiaId;
    }
    public Actaingreso(int periodoId, int materiaId, Date actaIngresoLimitePresentacion, Date actaIngresoFecha, String actaIngresoEstado, String actaIngresoObservaciones) {
       this.periodoId = periodoId;
       this.materiaId = materiaId;
       this.actaIngresoLimitePresentacion = actaIngresoLimitePresentacion;
       this.actaIngresoFecha = actaIngresoFecha;
       this.actaIngresoEstado = actaIngresoEstado;
       this.actaIngresoObservaciones = actaIngresoObservaciones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="actaIngresoId", unique=true, nullable=false)
    public Integer getActaIngresoId() {
        return this.actaIngresoId;
    }
    
    public void setActaIngresoId(Integer actaIngresoId) {
        this.actaIngresoId = actaIngresoId;
    }

    
    @Column(name="periodoId", nullable=false)
    public int getPeriodoId() {
        return this.periodoId;
    }
    
    public void setPeriodoId(int periodoId) {
        this.periodoId = periodoId;
    }

    
    @Column(name="materiaId", nullable=false)
    public int getMateriaId() {
        return this.materiaId;
    }
    
    public void setMateriaId(int materiaId) {
        this.materiaId = materiaId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="actaIngresoLimitePresentacion", length=10)
    public Date getActaIngresoLimitePresentacion() {
        return this.actaIngresoLimitePresentacion;
    }
    
    public void setActaIngresoLimitePresentacion(Date actaIngresoLimitePresentacion) {
        this.actaIngresoLimitePresentacion = actaIngresoLimitePresentacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="actaIngresoFecha", length=10)
    public Date getActaIngresoFecha() {
        return this.actaIngresoFecha;
    }
    
    public void setActaIngresoFecha(Date actaIngresoFecha) {
        this.actaIngresoFecha = actaIngresoFecha;
    }

    
    @Column(name="actaIngresoEstado", length=2)
    public String getActaIngresoEstado() {
        return this.actaIngresoEstado;
    }
    
    public void setActaIngresoEstado(String actaIngresoEstado) {
        this.actaIngresoEstado = actaIngresoEstado;
    }

    
    @Column(name="actaIngresoObservaciones", length=250)
    public String getActaIngresoObservaciones() {
        return this.actaIngresoObservaciones;
    }
    
    public void setActaIngresoObservaciones(String actaIngresoObservaciones) {
        this.actaIngresoObservaciones = actaIngresoObservaciones;
    }




}


