package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actaregularidad generated by hbm2java
 */
@Entity
@Table(name="actaregularidad"
    ,catalog="sgaundec"
)
public class Actaregularidad  implements java.io.Serializable {


     private Integer actaRegularidadId;
     private int periodoId;
     private int materiaId;
     private Date actaRegularidadLimitePresentacion;
     private Date actaRegularidadFecha;
     private String actaRegularidadEstado;
     private String actaRegularidadObservaciones;

    public Actaregularidad() {
    }

	
    public Actaregularidad(int periodoId, int materiaId) {
        this.periodoId = periodoId;
        this.materiaId = materiaId;
    }
    public Actaregularidad(int periodoId, int materiaId, Date actaRegularidadLimitePresentacion, Date actaRegularidadFecha, String actaRegularidadEstado, String actaRegularidadObservaciones) {
       this.periodoId = periodoId;
       this.materiaId = materiaId;
       this.actaRegularidadLimitePresentacion = actaRegularidadLimitePresentacion;
       this.actaRegularidadFecha = actaRegularidadFecha;
       this.actaRegularidadEstado = actaRegularidadEstado;
       this.actaRegularidadObservaciones = actaRegularidadObservaciones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="actaRegularidadId", unique=true, nullable=false)
    public Integer getActaRegularidadId() {
        return this.actaRegularidadId;
    }
    
    public void setActaRegularidadId(Integer actaRegularidadId) {
        this.actaRegularidadId = actaRegularidadId;
    }

    
    @Column(name="periodoId", nullable=false)
    public int getPeriodoId() {
        return this.periodoId;
    }
    
    public void setPeriodoId(int periodoId) {
        this.periodoId = periodoId;
    }

    
    @Column(name="materiaId", nullable=false)
    public int getMateriaId() {
        return this.materiaId;
    }
    
    public void setMateriaId(int materiaId) {
        this.materiaId = materiaId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="actaRegularidadLimitePresentacion", length=10)
    public Date getActaRegularidadLimitePresentacion() {
        return this.actaRegularidadLimitePresentacion;
    }
    
    public void setActaRegularidadLimitePresentacion(Date actaRegularidadLimitePresentacion) {
        this.actaRegularidadLimitePresentacion = actaRegularidadLimitePresentacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="actaRegularidadFecha", length=10)
    public Date getActaRegularidadFecha() {
        return this.actaRegularidadFecha;
    }
    
    public void setActaRegularidadFecha(Date actaRegularidadFecha) {
        this.actaRegularidadFecha = actaRegularidadFecha;
    }

    
    @Column(name="actaRegularidadEstado", length=2)
    public String getActaRegularidadEstado() {
        return this.actaRegularidadEstado;
    }
    
    public void setActaRegularidadEstado(String actaRegularidadEstado) {
        this.actaRegularidadEstado = actaRegularidadEstado;
    }

    
    @Column(name="actaRegularidadObservaciones", length=250)
    public String getActaRegularidadObservaciones() {
        return this.actaRegularidadObservaciones;
    }
    
    public void setActaRegularidadObservaciones(String actaRegularidadObservaciones) {
        this.actaRegularidadObservaciones = actaRegularidadObservaciones;
    }




}


