package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name="alumno"
    ,catalog="sgaundec"
)
public class Alumno  implements java.io.Serializable {


     private Integer alumnoId;
     private int personaId;
     private Date alumnoFecha;
     private String alumnoMatricula;
     private Date alumnoFechaLibreta;
     private String alumnoOtrosEstudios;
     private Integer alumnoNivelOtrosEstudios;
     private Integer cicloAno;
     private Date alumnoFechaBaja;
     private Date alumnoFechaEgreso;

    public Alumno() {
    }

	
    public Alumno(int personaId) {
        this.personaId = personaId;
    }
    public Alumno(int personaId, Date alumnoFecha, String alumnoMatricula, Date alumnoFechaLibreta, String alumnoOtrosEstudios, Integer alumnoNivelOtrosEstudios, Integer cicloAno, Date alumnoFechaBaja, Date alumnoFechaEgreso) {
       this.personaId = personaId;
       this.alumnoFecha = alumnoFecha;
       this.alumnoMatricula = alumnoMatricula;
       this.alumnoFechaLibreta = alumnoFechaLibreta;
       this.alumnoOtrosEstudios = alumnoOtrosEstudios;
       this.alumnoNivelOtrosEstudios = alumnoNivelOtrosEstudios;
       this.cicloAno = cicloAno;
       this.alumnoFechaBaja = alumnoFechaBaja;
       this.alumnoFechaEgreso = alumnoFechaEgreso;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="alumnoId", unique=true, nullable=false)
    public Integer getAlumnoId() {
        return this.alumnoId;
    }
    
    public void setAlumnoId(Integer alumnoId) {
        this.alumnoId = alumnoId;
    }

    
    @Column(name="personaId", nullable=false)
    public int getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(int personaId) {
        this.personaId = personaId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="alumnoFecha", length=10)
    public Date getAlumnoFecha() {
        return this.alumnoFecha;
    }
    
    public void setAlumnoFecha(Date alumnoFecha) {
        this.alumnoFecha = alumnoFecha;
    }

    
    @Column(name="alumnoMatricula", length=20)
    public String getAlumnoMatricula() {
        return this.alumnoMatricula;
    }
    
    public void setAlumnoMatricula(String alumnoMatricula) {
        this.alumnoMatricula = alumnoMatricula;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="alumnoFechaLibreta", length=10)
    public Date getAlumnoFechaLibreta() {
        return this.alumnoFechaLibreta;
    }
    
    public void setAlumnoFechaLibreta(Date alumnoFechaLibreta) {
        this.alumnoFechaLibreta = alumnoFechaLibreta;
    }

    
    @Column(name="alumnoOtrosEstudios", length=150)
    public String getAlumnoOtrosEstudios() {
        return this.alumnoOtrosEstudios;
    }
    
    public void setAlumnoOtrosEstudios(String alumnoOtrosEstudios) {
        this.alumnoOtrosEstudios = alumnoOtrosEstudios;
    }

    
    @Column(name="alumnoNivelOtrosEstudios")
    public Integer getAlumnoNivelOtrosEstudios() {
        return this.alumnoNivelOtrosEstudios;
    }
    
    public void setAlumnoNivelOtrosEstudios(Integer alumnoNivelOtrosEstudios) {
        this.alumnoNivelOtrosEstudios = alumnoNivelOtrosEstudios;
    }

    
    @Column(name="cicloAno")
    public Integer getCicloAno() {
        return this.cicloAno;
    }
    
    public void setCicloAno(Integer cicloAno) {
        this.cicloAno = cicloAno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="alumnoFechaBaja", length=10)
    public Date getAlumnoFechaBaja() {
        return this.alumnoFechaBaja;
    }
    
    public void setAlumnoFechaBaja(Date alumnoFechaBaja) {
        this.alumnoFechaBaja = alumnoFechaBaja;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="alumnoFechaEgreso", length=10)
    public Date getAlumnoFechaEgreso() {
        return this.alumnoFechaEgreso;
    }
    
    public void setAlumnoFechaEgreso(Date alumnoFechaEgreso) {
        this.alumnoFechaEgreso = alumnoFechaEgreso;
    }




}


