package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Carrera generated by hbm2java
 */
@Entity
@Table(name="carrera"
    ,catalog="sgaundec"
)
public class Carrera  implements java.io.Serializable {


     private Integer carreraId;
     private String carreraNombre;
     private Integer carreraMatriculaInicial;

    public Carrera() {
    }

    public Carrera(String carreraNombre, Integer carreraMatriculaInicial) {
       this.carreraNombre = carreraNombre;
       this.carreraMatriculaInicial = carreraMatriculaInicial;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="carreraId", unique=true, nullable=false)
    public Integer getCarreraId() {
        return this.carreraId;
    }
    
    public void setCarreraId(Integer carreraId) {
        this.carreraId = carreraId;
    }

    
    @Column(name="carreraNombre", length=250)
    public String getCarreraNombre() {
        return this.carreraNombre;
    }
    
    public void setCarreraNombre(String carreraNombre) {
        this.carreraNombre = carreraNombre;
    }

    
    @Column(name="carreraMatriculaInicial")
    public Integer getCarreraMatriculaInicial() {
        return this.carreraMatriculaInicial;
    }
    
    public void setCarreraMatriculaInicial(Integer carreraMatriculaInicial) {
        this.carreraMatriculaInicial = carreraMatriculaInicial;
    }




}


