package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ciclo generated by hbm2java
 */
@Entity
@Table(name="ciclo"
    ,catalog="sgaundec"
)
public class Ciclo  implements java.io.Serializable {


     private Integer cicloAno;
     private Date cicloFechaInicio;
     private Date cicloFechaFin;

    public Ciclo() {
    }

    public Ciclo(Date cicloFechaInicio, Date cicloFechaFin) {
       this.cicloFechaInicio = cicloFechaInicio;
       this.cicloFechaFin = cicloFechaFin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cicloAno", unique=true, nullable=false)
    public Integer getCicloAno() {
        return this.cicloAno;
    }
    
    public void setCicloAno(Integer cicloAno) {
        this.cicloAno = cicloAno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cicloFechaInicio", length=10)
    public Date getCicloFechaInicio() {
        return this.cicloFechaInicio;
    }
    
    public void setCicloFechaInicio(Date cicloFechaInicio) {
        this.cicloFechaInicio = cicloFechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cicloFechaFin", length=10)
    public Date getCicloFechaFin() {
        return this.cicloFechaFin;
    }
    
    public void setCicloFechaFin(Date cicloFechaFin) {
        this.cicloFechaFin = cicloFechaFin;
    }




}


