package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Correlatividad generated by hbm2java
 */
@Entity
@Table(name="correlatividad"
    ,catalog="sgaundec"
)
public class Correlatividad  implements java.io.Serializable {


     private CorrelatividadId id;
     private Integer correlatividadCursada;
     private Integer correlatividadFinales;
     private Integer correlatividadAprobada;

    public Correlatividad() {
    }

	
    public Correlatividad(CorrelatividadId id) {
        this.id = id;
    }
    public Correlatividad(CorrelatividadId id, Integer correlatividadCursada, Integer correlatividadFinales, Integer correlatividadAprobada) {
       this.id = id;
       this.correlatividadCursada = correlatividadCursada;
       this.correlatividadFinales = correlatividadFinales;
       this.correlatividadAprobada = correlatividadAprobada;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="materiaId", column=@Column(name="materiaId", nullable=false) ), 
        @AttributeOverride(name="esCorrelativaDe", column=@Column(name="esCorrelativaDe", nullable=false) ) } )
    public CorrelatividadId getId() {
        return this.id;
    }
    
    public void setId(CorrelatividadId id) {
        this.id = id;
    }

    
    @Column(name="correlatividadCursada")
    public Integer getCorrelatividadCursada() {
        return this.correlatividadCursada;
    }
    
    public void setCorrelatividadCursada(Integer correlatividadCursada) {
        this.correlatividadCursada = correlatividadCursada;
    }

    
    @Column(name="correlatividadFinales")
    public Integer getCorrelatividadFinales() {
        return this.correlatividadFinales;
    }
    
    public void setCorrelatividadFinales(Integer correlatividadFinales) {
        this.correlatividadFinales = correlatividadFinales;
    }

    
    @Column(name="correlatividadAprobada")
    public Integer getCorrelatividadAprobada() {
        return this.correlatividadAprobada;
    }
    
    public void setCorrelatividadAprobada(Integer correlatividadAprobada) {
        this.correlatividadAprobada = correlatividadAprobada;
    }




}


