package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,catalog="sgaundec"
)
public class Departamento  implements java.io.Serializable {


     private Integer departamentoId;
     private String departamentoNombre;
     private Integer provinciaId;

    public Departamento() {
    }

    public Departamento(String departamentoNombre, Integer provinciaId) {
       this.departamentoNombre = departamentoNombre;
       this.provinciaId = provinciaId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="departamentoId", unique=true, nullable=false)
    public Integer getDepartamentoId() {
        return this.departamentoId;
    }
    
    public void setDepartamentoId(Integer departamentoId) {
        this.departamentoId = departamentoId;
    }

    
    @Column(name="departamentoNombre", length=60)
    public String getDepartamentoNombre() {
        return this.departamentoNombre;
    }
    
    public void setDepartamentoNombre(String departamentoNombre) {
        this.departamentoNombre = departamentoNombre;
    }

    
    @Column(name="provinciaId")
    public Integer getProvinciaId() {
        return this.provinciaId;
    }
    
    public void setProvinciaId(Integer provinciaId) {
        this.provinciaId = provinciaId;
    }




}


