package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name="docente"
    ,catalog="sgaundec"
)
public class Docente  implements java.io.Serializable {


     private Integer docenteId;
     private String docenteTitulo;
     private String docenteNombre;
     private String docenteApellido;
     private String docenteTelefono;
     private String docenteEmail;
     private String docenteObservaciones;

    public Docente() {
    }

	
    public Docente(String docenteTitulo, String docenteNombre, String docenteApellido) {
        this.docenteTitulo = docenteTitulo;
        this.docenteNombre = docenteNombre;
        this.docenteApellido = docenteApellido;
    }
    public Docente(String docenteTitulo, String docenteNombre, String docenteApellido, String docenteTelefono, String docenteEmail, String docenteObservaciones) {
       this.docenteTitulo = docenteTitulo;
       this.docenteNombre = docenteNombre;
       this.docenteApellido = docenteApellido;
       this.docenteTelefono = docenteTelefono;
       this.docenteEmail = docenteEmail;
       this.docenteObservaciones = docenteObservaciones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="docenteId", unique=true, nullable=false)
    public Integer getDocenteId() {
        return this.docenteId;
    }
    
    public void setDocenteId(Integer docenteId) {
        this.docenteId = docenteId;
    }

    
    @Column(name="docenteTitulo", nullable=false, length=30)
    public String getDocenteTitulo() {
        return this.docenteTitulo;
    }
    
    public void setDocenteTitulo(String docenteTitulo) {
        this.docenteTitulo = docenteTitulo;
    }

    
    @Column(name="docenteNombre", nullable=false, length=60)
    public String getDocenteNombre() {
        return this.docenteNombre;
    }
    
    public void setDocenteNombre(String docenteNombre) {
        this.docenteNombre = docenteNombre;
    }

    
    @Column(name="docenteApellido", nullable=false, length=60)
    public String getDocenteApellido() {
        return this.docenteApellido;
    }
    
    public void setDocenteApellido(String docenteApellido) {
        this.docenteApellido = docenteApellido;
    }

    
    @Column(name="docenteTelefono", length=30)
    public String getDocenteTelefono() {
        return this.docenteTelefono;
    }
    
    public void setDocenteTelefono(String docenteTelefono) {
        this.docenteTelefono = docenteTelefono;
    }

    
    @Column(name="docenteEmail", length=60)
    public String getDocenteEmail() {
        return this.docenteEmail;
    }
    
    public void setDocenteEmail(String docenteEmail) {
        this.docenteEmail = docenteEmail;
    }

    
    @Column(name="docenteObservaciones", length=150)
    public String getDocenteObservaciones() {
        return this.docenteObservaciones;
    }
    
    public void setDocenteObservaciones(String docenteObservaciones) {
        this.docenteObservaciones = docenteObservaciones;
    }




}


