package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Domicilio generated by hbm2java
 */
@Entity
@Table(name="domicilio"
    ,catalog="sgaundec"
)
public class Domicilio  implements java.io.Serializable {


     private Integer domicilioId;
     private int distritoId;
     private Integer personaId;
     private Integer domicilioTipo;
     private String domicilioCalle;
     private String domicilioNumero;
     private String domicilioBarrio;
     private String domicilioTelefono;
     private Date domicilioFecha;

    public Domicilio() {
    }

	
    public Domicilio(int distritoId) {
        this.distritoId = distritoId;
    }
    public Domicilio(int distritoId, Integer personaId, Integer domicilioTipo, String domicilioCalle, String domicilioNumero, String domicilioBarrio, String domicilioTelefono, Date domicilioFecha) {
       this.distritoId = distritoId;
       this.personaId = personaId;
       this.domicilioTipo = domicilioTipo;
       this.domicilioCalle = domicilioCalle;
       this.domicilioNumero = domicilioNumero;
       this.domicilioBarrio = domicilioBarrio;
       this.domicilioTelefono = domicilioTelefono;
       this.domicilioFecha = domicilioFecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="domicilioId", unique=true, nullable=false)
    public Integer getDomicilioId() {
        return this.domicilioId;
    }
    
    public void setDomicilioId(Integer domicilioId) {
        this.domicilioId = domicilioId;
    }

    
    @Column(name="distritoId", nullable=false)
    public int getDistritoId() {
        return this.distritoId;
    }
    
    public void setDistritoId(int distritoId) {
        this.distritoId = distritoId;
    }

    
    @Column(name="personaId")
    public Integer getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(Integer personaId) {
        this.personaId = personaId;
    }

    
    @Column(name="domicilioTipo")
    public Integer getDomicilioTipo() {
        return this.domicilioTipo;
    }
    
    public void setDomicilioTipo(Integer domicilioTipo) {
        this.domicilioTipo = domicilioTipo;
    }

    
    @Column(name="domicilioCalle", length=80)
    public String getDomicilioCalle() {
        return this.domicilioCalle;
    }
    
    public void setDomicilioCalle(String domicilioCalle) {
        this.domicilioCalle = domicilioCalle;
    }

    
    @Column(name="domicilioNumero", length=10)
    public String getDomicilioNumero() {
        return this.domicilioNumero;
    }
    
    public void setDomicilioNumero(String domicilioNumero) {
        this.domicilioNumero = domicilioNumero;
    }

    
    @Column(name="domicilioBarrio", length=60)
    public String getDomicilioBarrio() {
        return this.domicilioBarrio;
    }
    
    public void setDomicilioBarrio(String domicilioBarrio) {
        this.domicilioBarrio = domicilioBarrio;
    }

    
    @Column(name="domicilioTelefono", length=30)
    public String getDomicilioTelefono() {
        return this.domicilioTelefono;
    }
    
    public void setDomicilioTelefono(String domicilioTelefono) {
        this.domicilioTelefono = domicilioTelefono;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="domicilioFecha", length=10)
    public Date getDomicilioFecha() {
        return this.domicilioFecha;
    }
    
    public void setDomicilioFecha(Date domicilioFecha) {
        this.domicilioFecha = domicilioFecha;
    }




}


