package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Egresosecundario generated by hbm2java
 */
@Entity
@Table(name="egresosecundario"
    ,catalog="sgaundec"
)
public class Egresosecundario  implements java.io.Serializable {


     private int personaId;
     private int escuelaId;
     private int tituloId;
     private Integer egresoSecundarioAno;

    public Egresosecundario() {
    }

	
    public Egresosecundario(int personaId, int escuelaId, int tituloId) {
        this.personaId = personaId;
        this.escuelaId = escuelaId;
        this.tituloId = tituloId;
    }
    public Egresosecundario(int personaId, int escuelaId, int tituloId, Integer egresoSecundarioAno) {
       this.personaId = personaId;
       this.escuelaId = escuelaId;
       this.tituloId = tituloId;
       this.egresoSecundarioAno = egresoSecundarioAno;
    }
   
     @Id 

    
    @Column(name="personaId", unique=true, nullable=false)
    public int getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(int personaId) {
        this.personaId = personaId;
    }

    
    @Column(name="escuelaId", nullable=false)
    public int getEscuelaId() {
        return this.escuelaId;
    }
    
    public void setEscuelaId(int escuelaId) {
        this.escuelaId = escuelaId;
    }

    
    @Column(name="tituloId", nullable=false)
    public int getTituloId() {
        return this.tituloId;
    }
    
    public void setTituloId(int tituloId) {
        this.tituloId = tituloId;
    }

    
    @Column(name="egresoSecundarioAno")
    public Integer getEgresoSecundarioAno() {
        return this.egresoSecundarioAno;
    }
    
    public void setEgresoSecundarioAno(Integer egresoSecundarioAno) {
        this.egresoSecundarioAno = egresoSecundarioAno;
    }




}


