package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Encuesta generated by hbm2java
 */
@Entity
@Table(name="encuesta"
    ,catalog="sgaundec"
)
public class Encuesta  implements java.io.Serializable {


     private EncuestaId id;
     private Integer encuestaTrabaja;
     private Integer encuestaTrabajaHs;
     private Integer encuestaTrabajaBanda;
     private Integer encuestaTrabajaRelacion;
     private Integer encuestaAyudaFamiliar;
     private Integer encuestaBeca;
     private Integer encuestaVehiculo;
     private Date encuestaFecha;

    public Encuesta() {
    }

	
    public Encuesta(EncuestaId id) {
        this.id = id;
    }
    public Encuesta(EncuestaId id, Integer encuestaTrabaja, Integer encuestaTrabajaHs, Integer encuestaTrabajaBanda, Integer encuestaTrabajaRelacion, Integer encuestaAyudaFamiliar, Integer encuestaBeca, Integer encuestaVehiculo, Date encuestaFecha) {
       this.id = id;
       this.encuestaTrabaja = encuestaTrabaja;
       this.encuestaTrabajaHs = encuestaTrabajaHs;
       this.encuestaTrabajaBanda = encuestaTrabajaBanda;
       this.encuestaTrabajaRelacion = encuestaTrabajaRelacion;
       this.encuestaAyudaFamiliar = encuestaAyudaFamiliar;
       this.encuestaBeca = encuestaBeca;
       this.encuestaVehiculo = encuestaVehiculo;
       this.encuestaFecha = encuestaFecha;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="encuestaId", column=@Column(name="encuestaId", nullable=false) ), 
        @AttributeOverride(name="inscripcionId", column=@Column(name="inscripcionId", nullable=false) ) } )
    public EncuestaId getId() {
        return this.id;
    }
    
    public void setId(EncuestaId id) {
        this.id = id;
    }

    
    @Column(name="encuestaTrabaja")
    public Integer getEncuestaTrabaja() {
        return this.encuestaTrabaja;
    }
    
    public void setEncuestaTrabaja(Integer encuestaTrabaja) {
        this.encuestaTrabaja = encuestaTrabaja;
    }

    
    @Column(name="encuestaTrabajaHs")
    public Integer getEncuestaTrabajaHs() {
        return this.encuestaTrabajaHs;
    }
    
    public void setEncuestaTrabajaHs(Integer encuestaTrabajaHs) {
        this.encuestaTrabajaHs = encuestaTrabajaHs;
    }

    
    @Column(name="encuestaTrabajaBanda")
    public Integer getEncuestaTrabajaBanda() {
        return this.encuestaTrabajaBanda;
    }
    
    public void setEncuestaTrabajaBanda(Integer encuestaTrabajaBanda) {
        this.encuestaTrabajaBanda = encuestaTrabajaBanda;
    }

    
    @Column(name="encuestaTrabajaRelacion")
    public Integer getEncuestaTrabajaRelacion() {
        return this.encuestaTrabajaRelacion;
    }
    
    public void setEncuestaTrabajaRelacion(Integer encuestaTrabajaRelacion) {
        this.encuestaTrabajaRelacion = encuestaTrabajaRelacion;
    }

    
    @Column(name="encuestaAyudaFamiliar")
    public Integer getEncuestaAyudaFamiliar() {
        return this.encuestaAyudaFamiliar;
    }
    
    public void setEncuestaAyudaFamiliar(Integer encuestaAyudaFamiliar) {
        this.encuestaAyudaFamiliar = encuestaAyudaFamiliar;
    }

    
    @Column(name="encuestaBeca")
    public Integer getEncuestaBeca() {
        return this.encuestaBeca;
    }
    
    public void setEncuestaBeca(Integer encuestaBeca) {
        this.encuestaBeca = encuestaBeca;
    }

    
    @Column(name="encuestaVehiculo")
    public Integer getEncuestaVehiculo() {
        return this.encuestaVehiculo;
    }
    
    public void setEncuestaVehiculo(Integer encuestaVehiculo) {
        this.encuestaVehiculo = encuestaVehiculo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="encuestaFecha", length=10)
    public Date getEncuestaFecha() {
        return this.encuestaFecha;
    }
    
    public void setEncuestaFecha(Date encuestaFecha) {
        this.encuestaFecha = encuestaFecha;
    }




}


