package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Equivalencia generated by hbm2java
 */
@Entity
@Table(name="equivalencia"
    ,catalog="sgaundec"
)
public class Equivalencia  implements java.io.Serializable {


     private Integer equivalenciaId;
     private int materiaId;
     private Integer equivalenciaTipo;
     private Integer expedienteId;
     private Integer equivalenciaNota;

    public Equivalencia() {
    }

	
    public Equivalencia(int materiaId) {
        this.materiaId = materiaId;
    }
    public Equivalencia(int materiaId, Integer equivalenciaTipo, Integer expedienteId, Integer equivalenciaNota) {
       this.materiaId = materiaId;
       this.equivalenciaTipo = equivalenciaTipo;
       this.expedienteId = expedienteId;
       this.equivalenciaNota = equivalenciaNota;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="equivalenciaId", unique=true, nullable=false)
    public Integer getEquivalenciaId() {
        return this.equivalenciaId;
    }
    
    public void setEquivalenciaId(Integer equivalenciaId) {
        this.equivalenciaId = equivalenciaId;
    }

    
    @Column(name="materiaId", nullable=false)
    public int getMateriaId() {
        return this.materiaId;
    }
    
    public void setMateriaId(int materiaId) {
        this.materiaId = materiaId;
    }

    
    @Column(name="equivalenciaTipo")
    public Integer getEquivalenciaTipo() {
        return this.equivalenciaTipo;
    }
    
    public void setEquivalenciaTipo(Integer equivalenciaTipo) {
        this.equivalenciaTipo = equivalenciaTipo;
    }

    
    @Column(name="expedienteId")
    public Integer getExpedienteId() {
        return this.expedienteId;
    }
    
    public void setExpedienteId(Integer expedienteId) {
        this.expedienteId = expedienteId;
    }

    
    @Column(name="equivalenciaNota")
    public Integer getEquivalenciaNota() {
        return this.equivalenciaNota;
    }
    
    public void setEquivalenciaNota(Integer equivalenciaNota) {
        this.equivalenciaNota = equivalenciaNota;
    }




}


