package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Escuela generated by hbm2java
 */
@Entity
@Table(name="escuela"
    ,catalog="sgaundec"
)
public class Escuela  implements java.io.Serializable {


     private Integer escuelaId;
     private String escuelaNombre;
     private Integer distritoId;
     private Integer escuelaTipoId;

    public Escuela() {
    }

    public Escuela(String escuelaNombre, Integer distritoId, Integer escuelaTipoId) {
       this.escuelaNombre = escuelaNombre;
       this.distritoId = distritoId;
       this.escuelaTipoId = escuelaTipoId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="escuelaId", unique=true, nullable=false)
    public Integer getEscuelaId() {
        return this.escuelaId;
    }
    
    public void setEscuelaId(Integer escuelaId) {
        this.escuelaId = escuelaId;
    }

    
    @Column(name="escuelaNombre", length=70)
    public String getEscuelaNombre() {
        return this.escuelaNombre;
    }
    
    public void setEscuelaNombre(String escuelaNombre) {
        this.escuelaNombre = escuelaNombre;
    }

    
    @Column(name="distritoId")
    public Integer getDistritoId() {
        return this.distritoId;
    }
    
    public void setDistritoId(Integer distritoId) {
        this.distritoId = distritoId;
    }

    
    @Column(name="escuelaTipoId")
    public Integer getEscuelaTipoId() {
        return this.escuelaTipoId;
    }
    
    public void setEscuelaTipoId(Integer escuelaTipoId) {
        this.escuelaTipoId = escuelaTipoId;
    }




}


