package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Escuelatipo generated by hbm2java
 */
@Entity
@Table(name="escuelatipo"
    ,catalog="sgaundec"
)
public class Escuelatipo  implements java.io.Serializable {


     private Integer escuelaTipoId;
     private String escuelaTipoDescripcion;

    public Escuelatipo() {
    }

    public Escuelatipo(String escuelaTipoDescripcion) {
       this.escuelaTipoDescripcion = escuelaTipoDescripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="escuelaTipoId", unique=true, nullable=false)
    public Integer getEscuelaTipoId() {
        return this.escuelaTipoId;
    }
    
    public void setEscuelaTipoId(Integer escuelaTipoId) {
        this.escuelaTipoId = escuelaTipoId;
    }

    
    @Column(name="escuelaTipoDescripcion", length=60)
    public String getEscuelaTipoDescripcion() {
        return this.escuelaTipoDescripcion;
    }
    
    public void setEscuelaTipoDescripcion(String escuelaTipoDescripcion) {
        this.escuelaTipoDescripcion = escuelaTipoDescripcion;
    }




}


