package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Expedientetipo generated by hbm2java
 */
@Entity
@Table(name="expedientetipo"
    ,catalog="sgaundec"
)
public class Expedientetipo  implements java.io.Serializable {


     private Integer expedienteTipoId;
     private String expedienteTipoDescripcion;

    public Expedientetipo() {
    }

    public Expedientetipo(String expedienteTipoDescripcion) {
       this.expedienteTipoDescripcion = expedienteTipoDescripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="expedienteTipoId", unique=true, nullable=false)
    public Integer getExpedienteTipoId() {
        return this.expedienteTipoId;
    }
    
    public void setExpedienteTipoId(Integer expedienteTipoId) {
        this.expedienteTipoId = expedienteTipoId;
    }

    
    @Column(name="expedienteTipoDescripcion", length=150)
    public String getExpedienteTipoDescripcion() {
        return this.expedienteTipoDescripcion;
    }
    
    public void setExpedienteTipoDescripcion(String expedienteTipoDescripcion) {
        this.expedienteTipoDescripcion = expedienteTipoDescripcion;
    }




}


