package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expediente generated by hbm2java
 */
@Entity
@Table(name="expediente"
    ,catalog="sgaundec"
)
public class Expediente  implements java.io.Serializable {


     private Integer expedienteId;
     private int inscriptoId;
     private int expedienteTipoId;
     private Integer expedienteDenominacionId;
     private String expedienteNumero;
     private Date expedienteFecha;
     private String expedienteObservaciones;
     private Date expedienteFechaRegistro;
     private Date expedienteFechaEntrada;
     private Date expedienteFechaSalida;
     private String expedienteNroResolucion;
     private Date expedienteFechaResolucion;

    public Expediente() {
    }

	
    public Expediente(int inscriptoId, int expedienteTipoId, String expedienteNroResolucion) {
        this.inscriptoId = inscriptoId;
        this.expedienteTipoId = expedienteTipoId;
        this.expedienteNroResolucion = expedienteNroResolucion;
    }
    public Expediente(int inscriptoId, int expedienteTipoId, Integer expedienteDenominacionId, String expedienteNumero, Date expedienteFecha, String expedienteObservaciones, Date expedienteFechaRegistro, Date expedienteFechaEntrada, Date expedienteFechaSalida, String expedienteNroResolucion, Date expedienteFechaResolucion) {
       this.inscriptoId = inscriptoId;
       this.expedienteTipoId = expedienteTipoId;
       this.expedienteDenominacionId = expedienteDenominacionId;
       this.expedienteNumero = expedienteNumero;
       this.expedienteFecha = expedienteFecha;
       this.expedienteObservaciones = expedienteObservaciones;
       this.expedienteFechaRegistro = expedienteFechaRegistro;
       this.expedienteFechaEntrada = expedienteFechaEntrada;
       this.expedienteFechaSalida = expedienteFechaSalida;
       this.expedienteNroResolucion = expedienteNroResolucion;
       this.expedienteFechaResolucion = expedienteFechaResolucion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="expedienteId", unique=true, nullable=false)
    public Integer getExpedienteId() {
        return this.expedienteId;
    }
    
    public void setExpedienteId(Integer expedienteId) {
        this.expedienteId = expedienteId;
    }

    
    @Column(name="inscriptoId", nullable=false)
    public int getInscriptoId() {
        return this.inscriptoId;
    }
    
    public void setInscriptoId(int inscriptoId) {
        this.inscriptoId = inscriptoId;
    }

    
    @Column(name="expedienteTipoId", nullable=false)
    public int getExpedienteTipoId() {
        return this.expedienteTipoId;
    }
    
    public void setExpedienteTipoId(int expedienteTipoId) {
        this.expedienteTipoId = expedienteTipoId;
    }

    
    @Column(name="expedienteDenominacionId")
    public Integer getExpedienteDenominacionId() {
        return this.expedienteDenominacionId;
    }
    
    public void setExpedienteDenominacionId(Integer expedienteDenominacionId) {
        this.expedienteDenominacionId = expedienteDenominacionId;
    }

    
    @Column(name="expedienteNumero", length=20)
    public String getExpedienteNumero() {
        return this.expedienteNumero;
    }
    
    public void setExpedienteNumero(String expedienteNumero) {
        this.expedienteNumero = expedienteNumero;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expedienteFecha", length=10)
    public Date getExpedienteFecha() {
        return this.expedienteFecha;
    }
    
    public void setExpedienteFecha(Date expedienteFecha) {
        this.expedienteFecha = expedienteFecha;
    }

    
    @Column(name="expedienteObservaciones", length=250)
    public String getExpedienteObservaciones() {
        return this.expedienteObservaciones;
    }
    
    public void setExpedienteObservaciones(String expedienteObservaciones) {
        this.expedienteObservaciones = expedienteObservaciones;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expedienteFechaRegistro", length=10)
    public Date getExpedienteFechaRegistro() {
        return this.expedienteFechaRegistro;
    }
    
    public void setExpedienteFechaRegistro(Date expedienteFechaRegistro) {
        this.expedienteFechaRegistro = expedienteFechaRegistro;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expedienteFechaEntrada", length=10)
    public Date getExpedienteFechaEntrada() {
        return this.expedienteFechaEntrada;
    }
    
    public void setExpedienteFechaEntrada(Date expedienteFechaEntrada) {
        this.expedienteFechaEntrada = expedienteFechaEntrada;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expedienteFechaSalida", length=10)
    public Date getExpedienteFechaSalida() {
        return this.expedienteFechaSalida;
    }
    
    public void setExpedienteFechaSalida(Date expedienteFechaSalida) {
        this.expedienteFechaSalida = expedienteFechaSalida;
    }

    
    @Column(name="expedienteNroResolucion", nullable=false, length=30)
    public String getExpedienteNroResolucion() {
        return this.expedienteNroResolucion;
    }
    
    public void setExpedienteNroResolucion(String expedienteNroResolucion) {
        this.expedienteNroResolucion = expedienteNroResolucion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expedienteFechaResolucion", length=10)
    public Date getExpedienteFechaResolucion() {
        return this.expedienteFechaResolucion;
    }
    
    public void setExpedienteFechaResolucion(Date expedienteFechaResolucion) {
        this.expedienteFechaResolucion = expedienteFechaResolucion;
    }




}


