package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Expedientedenominacion generated by hbm2java
 */
@Entity
@Table(name="expedientedenominacion"
    ,catalog="sgaundec"
)
public class Expedientedenominacion  implements java.io.Serializable {


     private Integer expedienteDenominacionId;
     private String expedienteDenominacionNombre;

    public Expedientedenominacion() {
    }

    public Expedientedenominacion(String expedienteDenominacionNombre) {
       this.expedienteDenominacionNombre = expedienteDenominacionNombre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="expedienteDenominacionId", unique=true, nullable=false)
    public Integer getExpedienteDenominacionId() {
        return this.expedienteDenominacionId;
    }
    
    public void setExpedienteDenominacionId(Integer expedienteDenominacionId) {
        this.expedienteDenominacionId = expedienteDenominacionId;
    }

    
    @Column(name="expedienteDenominacionNombre", length=200)
    public String getExpedienteDenominacionNombre() {
        return this.expedienteDenominacionNombre;
    }
    
    public void setExpedienteDenominacionNombre(String expedienteDenominacionNombre) {
        this.expedienteDenominacionNombre = expedienteDenominacionNombre;
    }




}


