package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Final generated by hbm2java
 */
@Entity
@Table(name="final"
    ,catalog="sgaundec"
)
public class Final  implements java.io.Serializable {


     private Integer finalId;
     private int inscriptoId;
     private int actaFinalId;
     private Character finalCondicion;
     private Integer finalNota;
     private int finalAusente;

    public Final() {
    }

	
    public Final(int inscriptoId, int actaFinalId, int finalAusente) {
        this.inscriptoId = inscriptoId;
        this.actaFinalId = actaFinalId;
        this.finalAusente = finalAusente;
    }
    public Final(int inscriptoId, int actaFinalId, Character finalCondicion, Integer finalNota, int finalAusente) {
       this.inscriptoId = inscriptoId;
       this.actaFinalId = actaFinalId;
       this.finalCondicion = finalCondicion;
       this.finalNota = finalNota;
       this.finalAusente = finalAusente;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="finalId", unique=true, nullable=false)
    public Integer getFinalId() {
        return this.finalId;
    }
    
    public void setFinalId(Integer finalId) {
        this.finalId = finalId;
    }

    
    @Column(name="inscriptoId", nullable=false)
    public int getInscriptoId() {
        return this.inscriptoId;
    }
    
    public void setInscriptoId(int inscriptoId) {
        this.inscriptoId = inscriptoId;
    }

    
    @Column(name="actaFinalId", nullable=false)
    public int getActaFinalId() {
        return this.actaFinalId;
    }
    
    public void setActaFinalId(int actaFinalId) {
        this.actaFinalId = actaFinalId;
    }

    
    @Column(name="finalCondicion", length=1)
    public Character getFinalCondicion() {
        return this.finalCondicion;
    }
    
    public void setFinalCondicion(Character finalCondicion) {
        this.finalCondicion = finalCondicion;
    }

    
    @Column(name="finalNota")
    public Integer getFinalNota() {
        return this.finalNota;
    }
    
    public void setFinalNota(Integer finalNota) {
        this.finalNota = finalNota;
    }

    
    @Column(name="finalAusente", nullable=false)
    public int getFinalAusente() {
        return this.finalAusente;
    }
    
    public void setFinalAusente(int finalAusente) {
        this.finalAusente = finalAusente;
    }




}


