package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Formulario generated by hbm2java
 */
@Entity
@Table(name="formulario"
    ,catalog="sgaundec"
)
public class Formulario  implements java.io.Serializable {


     private Integer formularioId;
     private String formularioNombre;
     private String formularioDescripcion;
     private String formularioMenu;
     private Integer formularioAccesoDefecto;

    public Formulario() {
    }

    public Formulario(String formularioNombre, String formularioDescripcion, String formularioMenu, Integer formularioAccesoDefecto) {
       this.formularioNombre = formularioNombre;
       this.formularioDescripcion = formularioDescripcion;
       this.formularioMenu = formularioMenu;
       this.formularioAccesoDefecto = formularioAccesoDefecto;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="formularioId", unique=true, nullable=false)
    public Integer getFormularioId() {
        return this.formularioId;
    }
    
    public void setFormularioId(Integer formularioId) {
        this.formularioId = formularioId;
    }

    
    @Column(name="formularioNombre", length=200)
    public String getFormularioNombre() {
        return this.formularioNombre;
    }
    
    public void setFormularioNombre(String formularioNombre) {
        this.formularioNombre = formularioNombre;
    }

    
    @Column(name="formularioDescripcion", length=200)
    public String getFormularioDescripcion() {
        return this.formularioDescripcion;
    }
    
    public void setFormularioDescripcion(String formularioDescripcion) {
        this.formularioDescripcion = formularioDescripcion;
    }

    
    @Column(name="formularioMenu", length=200)
    public String getFormularioMenu() {
        return this.formularioMenu;
    }
    
    public void setFormularioMenu(String formularioMenu) {
        this.formularioMenu = formularioMenu;
    }

    
    @Column(name="formularioAccesoDefecto")
    public Integer getFormularioAccesoDefecto() {
        return this.formularioAccesoDefecto;
    }
    
    public void setFormularioAccesoDefecto(Integer formularioAccesoDefecto) {
        this.formularioAccesoDefecto = formularioAccesoDefecto;
    }




}


