package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ingresoaprobacion generated by hbm2java
 */
@Entity
@Table(name="ingresoaprobacion"
    ,catalog="sgaundec"
)
public class Ingresoaprobacion  implements java.io.Serializable {


     private Integer ingresoAprobacionId;
     private int inscriptoId;
     private int actaIngresoId;
     private Double ingresoAprobacionAsistencia;
     private Integer ingresoAprobacionNota;
     private Character ingresoAprobacionCondicion;

    public Ingresoaprobacion() {
    }

	
    public Ingresoaprobacion(int inscriptoId, int actaIngresoId) {
        this.inscriptoId = inscriptoId;
        this.actaIngresoId = actaIngresoId;
    }
    public Ingresoaprobacion(int inscriptoId, int actaIngresoId, Double ingresoAprobacionAsistencia, Integer ingresoAprobacionNota, Character ingresoAprobacionCondicion) {
       this.inscriptoId = inscriptoId;
       this.actaIngresoId = actaIngresoId;
       this.ingresoAprobacionAsistencia = ingresoAprobacionAsistencia;
       this.ingresoAprobacionNota = ingresoAprobacionNota;
       this.ingresoAprobacionCondicion = ingresoAprobacionCondicion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ingresoAprobacionId", unique=true, nullable=false)
    public Integer getIngresoAprobacionId() {
        return this.ingresoAprobacionId;
    }
    
    public void setIngresoAprobacionId(Integer ingresoAprobacionId) {
        this.ingresoAprobacionId = ingresoAprobacionId;
    }

    
    @Column(name="inscriptoId", nullable=false)
    public int getInscriptoId() {
        return this.inscriptoId;
    }
    
    public void setInscriptoId(int inscriptoId) {
        this.inscriptoId = inscriptoId;
    }

    
    @Column(name="actaIngresoId", nullable=false)
    public int getActaIngresoId() {
        return this.actaIngresoId;
    }
    
    public void setActaIngresoId(int actaIngresoId) {
        this.actaIngresoId = actaIngresoId;
    }

    
    @Column(name="ingresoAprobacionAsistencia", precision=22, scale=0)
    public Double getIngresoAprobacionAsistencia() {
        return this.ingresoAprobacionAsistencia;
    }
    
    public void setIngresoAprobacionAsistencia(Double ingresoAprobacionAsistencia) {
        this.ingresoAprobacionAsistencia = ingresoAprobacionAsistencia;
    }

    
    @Column(name="ingresoAprobacionNota")
    public Integer getIngresoAprobacionNota() {
        return this.ingresoAprobacionNota;
    }
    
    public void setIngresoAprobacionNota(Integer ingresoAprobacionNota) {
        this.ingresoAprobacionNota = ingresoAprobacionNota;
    }

    
    @Column(name="ingresoAprobacionCondicion", length=1)
    public Character getIngresoAprobacionCondicion() {
        return this.ingresoAprobacionCondicion;
    }
    
    public void setIngresoAprobacionCondicion(Character ingresoAprobacionCondicion) {
        this.ingresoAprobacionCondicion = ingresoAprobacionCondicion;
    }




}


