package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inscripcionperiodo generated by hbm2java
 */
@Entity
@Table(name="inscripcionperiodo"
    ,catalog="sgaundec"
)
public class Inscripcionperiodo  implements java.io.Serializable {


     private Integer inscripcionPeriodoId;
     private int tipoInscripcionId;
     private int cicloAno;
     private Date inscripcionPeriodoDesde;
     private Date inscripcionPeriodoHasta;

    public Inscripcionperiodo() {
    }

	
    public Inscripcionperiodo(int tipoInscripcionId, int cicloAno) {
        this.tipoInscripcionId = tipoInscripcionId;
        this.cicloAno = cicloAno;
    }
    public Inscripcionperiodo(int tipoInscripcionId, int cicloAno, Date inscripcionPeriodoDesde, Date inscripcionPeriodoHasta) {
       this.tipoInscripcionId = tipoInscripcionId;
       this.cicloAno = cicloAno;
       this.inscripcionPeriodoDesde = inscripcionPeriodoDesde;
       this.inscripcionPeriodoHasta = inscripcionPeriodoHasta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="inscripcionPeriodoId", unique=true, nullable=false)
    public Integer getInscripcionPeriodoId() {
        return this.inscripcionPeriodoId;
    }
    
    public void setInscripcionPeriodoId(Integer inscripcionPeriodoId) {
        this.inscripcionPeriodoId = inscripcionPeriodoId;
    }

    
    @Column(name="tipoInscripcionId", nullable=false)
    public int getTipoInscripcionId() {
        return this.tipoInscripcionId;
    }
    
    public void setTipoInscripcionId(int tipoInscripcionId) {
        this.tipoInscripcionId = tipoInscripcionId;
    }

    
    @Column(name="cicloAno", nullable=false)
    public int getCicloAno() {
        return this.cicloAno;
    }
    
    public void setCicloAno(int cicloAno) {
        this.cicloAno = cicloAno;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="inscripcionPeriodoDesde", length=10)
    public Date getInscripcionPeriodoDesde() {
        return this.inscripcionPeriodoDesde;
    }
    
    public void setInscripcionPeriodoDesde(Date inscripcionPeriodoDesde) {
        this.inscripcionPeriodoDesde = inscripcionPeriodoDesde;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="inscripcionPeriodoHasta", length=10)
    public Date getInscripcionPeriodoHasta() {
        return this.inscripcionPeriodoHasta;
    }
    
    public void setInscripcionPeriodoHasta(Date inscripcionPeriodoHasta) {
        this.inscripcionPeriodoHasta = inscripcionPeriodoHasta;
    }




}


