package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inscripcion generated by hbm2java
 */
@Entity
@Table(name="inscripcion"
    ,catalog="sgaundec"
)
public class Inscripcion  implements java.io.Serializable {


     private Integer inscripcionId;
     private int inscriptoId;
     private int cicloAno;
     private Integer tipoInscripcionId;
     private Date inscripcionFecha;
     private String inscripcionObservaciones;

    public Inscripcion() {
    }

	
    public Inscripcion(int inscriptoId, int cicloAno) {
        this.inscriptoId = inscriptoId;
        this.cicloAno = cicloAno;
    }
    public Inscripcion(int inscriptoId, int cicloAno, Integer tipoInscripcionId, Date inscripcionFecha, String inscripcionObservaciones) {
       this.inscriptoId = inscriptoId;
       this.cicloAno = cicloAno;
       this.tipoInscripcionId = tipoInscripcionId;
       this.inscripcionFecha = inscripcionFecha;
       this.inscripcionObservaciones = inscripcionObservaciones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="inscripcionId", unique=true, nullable=false)
    public Integer getInscripcionId() {
        return this.inscripcionId;
    }
    
    public void setInscripcionId(Integer inscripcionId) {
        this.inscripcionId = inscripcionId;
    }

    
    @Column(name="inscriptoId", nullable=false)
    public int getInscriptoId() {
        return this.inscriptoId;
    }
    
    public void setInscriptoId(int inscriptoId) {
        this.inscriptoId = inscriptoId;
    }

    
    @Column(name="cicloAno", nullable=false)
    public int getCicloAno() {
        return this.cicloAno;
    }
    
    public void setCicloAno(int cicloAno) {
        this.cicloAno = cicloAno;
    }

    
    @Column(name="tipoInscripcionId")
    public Integer getTipoInscripcionId() {
        return this.tipoInscripcionId;
    }
    
    public void setTipoInscripcionId(Integer tipoInscripcionId) {
        this.tipoInscripcionId = tipoInscripcionId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="inscripcionFecha", length=10)
    public Date getInscripcionFecha() {
        return this.inscripcionFecha;
    }
    
    public void setInscripcionFecha(Date inscripcionFecha) {
        this.inscripcionFecha = inscripcionFecha;
    }

    
    @Column(name="inscripcionObservaciones", length=65535)
    public String getInscripcionObservaciones() {
        return this.inscripcionObservaciones;
    }
    
    public void setInscripcionObservaciones(String inscripcionObservaciones) {
        this.inscripcionObservaciones = inscripcionObservaciones;
    }




}


