package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inscripto generated by hbm2java
 */
@Entity
@Table(name="inscripto"
    ,catalog="sgaundec"
)
public class Inscripto  implements java.io.Serializable {


     private Integer inscriptoId;
     private int planId;
     private int alumnoId;
     private Date inscriptoFecha;

    public Inscripto() {
    }

	
    public Inscripto(int planId, int alumnoId) {
        this.planId = planId;
        this.alumnoId = alumnoId;
    }
    public Inscripto(int planId, int alumnoId, Date inscriptoFecha) {
       this.planId = planId;
       this.alumnoId = alumnoId;
       this.inscriptoFecha = inscriptoFecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="inscriptoId", unique=true, nullable=false)
    public Integer getInscriptoId() {
        return this.inscriptoId;
    }
    
    public void setInscriptoId(Integer inscriptoId) {
        this.inscriptoId = inscriptoId;
    }

    
    @Column(name="planId", nullable=false)
    public int getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(int planId) {
        this.planId = planId;
    }

    
    @Column(name="alumnoId", nullable=false)
    public int getAlumnoId() {
        return this.alumnoId;
    }
    
    public void setAlumnoId(int alumnoId) {
        this.alumnoId = alumnoId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="inscriptoFecha", length=10)
    public Date getInscriptoFecha() {
        return this.inscriptoFecha;
    }
    
    public void setInscriptoFecha(Date inscriptoFecha) {
        this.inscriptoFecha = inscriptoFecha;
    }




}


