package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Materia generated by hbm2java
 */
@Entity
@Table(name="materia"
    ,catalog="sgaundec"
)
public class Materia  implements java.io.Serializable {


     private Integer materiaId;
     private int planId;
     private Integer tipoMateriaId;
     private Integer materiaAno;
     private Integer materiaOrden;
     private String materiaNombre;
     private Integer materiaInscripciones;
     private Integer materiaPlanExigeFinal;
     private Integer materiaCursoIngreso;

    public Materia() {
    }

	
    public Materia(int planId) {
        this.planId = planId;
    }
    public Materia(int planId, Integer tipoMateriaId, Integer materiaAno, Integer materiaOrden, String materiaNombre, Integer materiaInscripciones, Integer materiaPlanExigeFinal, Integer materiaCursoIngreso) {
       this.planId = planId;
       this.tipoMateriaId = tipoMateriaId;
       this.materiaAno = materiaAno;
       this.materiaOrden = materiaOrden;
       this.materiaNombre = materiaNombre;
       this.materiaInscripciones = materiaInscripciones;
       this.materiaPlanExigeFinal = materiaPlanExigeFinal;
       this.materiaCursoIngreso = materiaCursoIngreso;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="materiaId", unique=true, nullable=false)
    public Integer getMateriaId() {
        return this.materiaId;
    }
    
    public void setMateriaId(Integer materiaId) {
        this.materiaId = materiaId;
    }

    
    @Column(name="planId", nullable=false)
    public int getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(int planId) {
        this.planId = planId;
    }

    
    @Column(name="tipoMateriaId")
    public Integer getTipoMateriaId() {
        return this.tipoMateriaId;
    }
    
    public void setTipoMateriaId(Integer tipoMateriaId) {
        this.tipoMateriaId = tipoMateriaId;
    }

    
    @Column(name="materiaAno")
    public Integer getMateriaAno() {
        return this.materiaAno;
    }
    
    public void setMateriaAno(Integer materiaAno) {
        this.materiaAno = materiaAno;
    }

    
    @Column(name="materiaOrden")
    public Integer getMateriaOrden() {
        return this.materiaOrden;
    }
    
    public void setMateriaOrden(Integer materiaOrden) {
        this.materiaOrden = materiaOrden;
    }

    
    @Column(name="materiaNombre", length=100)
    public String getMateriaNombre() {
        return this.materiaNombre;
    }
    
    public void setMateriaNombre(String materiaNombre) {
        this.materiaNombre = materiaNombre;
    }

    
    @Column(name="materiaInscripciones")
    public Integer getMateriaInscripciones() {
        return this.materiaInscripciones;
    }
    
    public void setMateriaInscripciones(Integer materiaInscripciones) {
        this.materiaInscripciones = materiaInscripciones;
    }

    
    @Column(name="materiaPlanExigeFinal")
    public Integer getMateriaPlanExigeFinal() {
        return this.materiaPlanExigeFinal;
    }
    
    public void setMateriaPlanExigeFinal(Integer materiaPlanExigeFinal) {
        this.materiaPlanExigeFinal = materiaPlanExigeFinal;
    }

    
    @Column(name="materiaCursoIngreso")
    public Integer getMateriaCursoIngreso() {
        return this.materiaCursoIngreso;
    }
    
    public void setMateriaCursoIngreso(Integer materiaCursoIngreso) {
        this.materiaCursoIngreso = materiaCursoIngreso;
    }




}


