package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Materiaingreso generated by hbm2java
 */
@Entity
@Table(name="materiaingreso"
    ,catalog="sgaundec"
)
public class Materiaingreso  implements java.io.Serializable {


     private MateriaingresoId id;

    public Materiaingreso() {
    }

    public Materiaingreso(MateriaingresoId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="materiaIngresoId", column=@Column(name="materiaIngresoId", nullable=false) ), 
        @AttributeOverride(name="materiaId", column=@Column(name="materiaId", nullable=false) ), 
        @AttributeOverride(name="cicloAno", column=@Column(name="cicloAno", nullable=false) ) } )
    public MateriaingresoId getId() {
        return this.id;
    }
    
    public void setId(MateriaingresoId id) {
        this.id = id;
    }




}


