package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Nivel generated by hbm2java
 */
@Entity
@Table(name="nivel"
    ,catalog="sgaundec"
)
public class Nivel  implements java.io.Serializable {


     private Integer nivelId;
     private String nivelDescripcion;

    public Nivel() {
    }

    public Nivel(String nivelDescripcion) {
       this.nivelDescripcion = nivelDescripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="nivelId", unique=true, nullable=false)
    public Integer getNivelId() {
        return this.nivelId;
    }
    
    public void setNivelId(Integer nivelId) {
        this.nivelId = nivelId;
    }

    
    @Column(name="nivelDescripcion", length=60)
    public String getNivelDescripcion() {
        return this.nivelDescripcion;
    }
    
    public void setNivelDescripcion(String nivelDescripcion) {
        this.nivelDescripcion = nivelDescripcion;
    }




}


