package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Opcional generated by hbm2java
 */
@Entity
@Table(name="opcional"
    ,catalog="sgaundec"
)
public class Opcional  implements java.io.Serializable {


     private OpcionalId id;

    public Opcional() {
    }

    public Opcional(OpcionalId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="materiaId", column=@Column(name="materiaId", nullable=false) ), 
        @AttributeOverride(name="esOpcionalDe", column=@Column(name="esOpcionalDe") ) } )
    public OpcionalId getId() {
        return this.id;
    }
    
    public void setId(OpcionalId id) {
        this.id = id;
    }




}


