package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name="pais"
    ,catalog="sgaundec"
)
public class Pais  implements java.io.Serializable {


     private Integer paisId;
     private String paisNombre;

    public Pais() {
    }

    public Pais(String paisNombre) {
       this.paisNombre = paisNombre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="paisId", unique=true, nullable=false)
    public Integer getPaisId() {
        return this.paisId;
    }
    
    public void setPaisId(Integer paisId) {
        this.paisId = paisId;
    }

    
    @Column(name="paisNombre", length=60)
    public String getPaisNombre() {
        return this.paisNombre;
    }
    
    public void setPaisNombre(String paisNombre) {
        this.paisNombre = paisNombre;
    }




}


