package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Periodo generated by hbm2java
 */
@Entity
@Table(name="periodo"
    ,catalog="sgaundec"
)
public class Periodo  implements java.io.Serializable {


     private Integer periodoId;
     private int cicloAno;
     private int tipoMateriaId;
     private Date periodoDesde;
     private Date periodoHasta;

    public Periodo() {
    }

	
    public Periodo(int cicloAno, int tipoMateriaId) {
        this.cicloAno = cicloAno;
        this.tipoMateriaId = tipoMateriaId;
    }
    public Periodo(int cicloAno, int tipoMateriaId, Date periodoDesde, Date periodoHasta) {
       this.cicloAno = cicloAno;
       this.tipoMateriaId = tipoMateriaId;
       this.periodoDesde = periodoDesde;
       this.periodoHasta = periodoHasta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="periodoId", unique=true, nullable=false)
    public Integer getPeriodoId() {
        return this.periodoId;
    }
    
    public void setPeriodoId(Integer periodoId) {
        this.periodoId = periodoId;
    }

    
    @Column(name="cicloAno", nullable=false)
    public int getCicloAno() {
        return this.cicloAno;
    }
    
    public void setCicloAno(int cicloAno) {
        this.cicloAno = cicloAno;
    }

    
    @Column(name="tipoMateriaId", nullable=false)
    public int getTipoMateriaId() {
        return this.tipoMateriaId;
    }
    
    public void setTipoMateriaId(int tipoMateriaId) {
        this.tipoMateriaId = tipoMateriaId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="periodoDesde", length=10)
    public Date getPeriodoDesde() {
        return this.periodoDesde;
    }
    
    public void setPeriodoDesde(Date periodoDesde) {
        this.periodoDesde = periodoDesde;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="periodoHasta", length=10)
    public Date getPeriodoHasta() {
        return this.periodoHasta;
    }
    
    public void setPeriodoHasta(Date periodoHasta) {
        this.periodoHasta = periodoHasta;
    }




}


