package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name="persona"
    ,catalog="sgaundec"
)
public class Persona  implements java.io.Serializable {


     private Integer personaId;
     private int nivelId;
     private int distritoId;
     private String personaApellido;
     private String personaNombres;
     private String personaSexo;
     private Date personaFechaNacimiento;
     private int tipoDocumentoId;
     private int personaDocumento;
     private String personaEmail;

    public Persona() {
    }

	
    public Persona(int nivelId, int distritoId, String personaApellido, String personaNombres, String personaSexo, int tipoDocumentoId, int personaDocumento) {
        this.nivelId = nivelId;
        this.distritoId = distritoId;
        this.personaApellido = personaApellido;
        this.personaNombres = personaNombres;
        this.personaSexo = personaSexo;
        this.tipoDocumentoId = tipoDocumentoId;
        this.personaDocumento = personaDocumento;
    }
    public Persona(int nivelId, int distritoId, String personaApellido, String personaNombres, String personaSexo, Date personaFechaNacimiento, int tipoDocumentoId, int personaDocumento, String personaEmail) {
       this.nivelId = nivelId;
       this.distritoId = distritoId;
       this.personaApellido = personaApellido;
       this.personaNombres = personaNombres;
       this.personaSexo = personaSexo;
       this.personaFechaNacimiento = personaFechaNacimiento;
       this.tipoDocumentoId = tipoDocumentoId;
       this.personaDocumento = personaDocumento;
       this.personaEmail = personaEmail;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="personaId", unique=true, nullable=false)
    public Integer getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(Integer personaId) {
        this.personaId = personaId;
    }

    
    @Column(name="nivelId", nullable=false)
    public int getNivelId() {
        return this.nivelId;
    }
    
    public void setNivelId(int nivelId) {
        this.nivelId = nivelId;
    }

    
    @Column(name="distritoId", nullable=false)
    public int getDistritoId() {
        return this.distritoId;
    }
    
    public void setDistritoId(int distritoId) {
        this.distritoId = distritoId;
    }

    
    @Column(name="personaApellido", nullable=false, length=60)
    public String getPersonaApellido() {
        return this.personaApellido;
    }
    
    public void setPersonaApellido(String personaApellido) {
        this.personaApellido = personaApellido;
    }

    
    @Column(name="personaNombres", nullable=false, length=60)
    public String getPersonaNombres() {
        return this.personaNombres;
    }
    
    public void setPersonaNombres(String personaNombres) {
        this.personaNombres = personaNombres;
    }

    
    @Column(name="personaSexo", nullable=false, length=1)
    public String getPersonaSexo() {
        return this.personaSexo;
    }
    
    public void setPersonaSexo(String personaSexo) {
        this.personaSexo = personaSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="personaFechaNacimiento", length=10)
    public Date getPersonaFechaNacimiento() {
        return this.personaFechaNacimiento;
    }
    
    public void setPersonaFechaNacimiento(Date personaFechaNacimiento) {
        this.personaFechaNacimiento = personaFechaNacimiento;
    }

    
    @Column(name="TipoDocumentoId", nullable=false)
    public int getTipoDocumentoId() {
        return this.tipoDocumentoId;
    }
    
    public void setTipoDocumentoId(int tipoDocumentoId) {
        this.tipoDocumentoId = tipoDocumentoId;
    }

    
    @Column(name="personaDocumento", nullable=false)
    public int getPersonaDocumento() {
        return this.personaDocumento;
    }
    
    public void setPersonaDocumento(int personaDocumento) {
        this.personaDocumento = personaDocumento;
    }

    
    @Column(name="personaEmail", length=50)
    public String getPersonaEmail() {
        return this.personaEmail;
    }
    
    public void setPersonaEmail(String personaEmail) {
        this.personaEmail = personaEmail;
    }




}


