package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Planes generated by hbm2java
 */
@Entity
@Table(name="planes"
    ,catalog="sgaundec"
)
public class Planes  implements java.io.Serializable {


     private Integer planId;
     private int carreraId;
     private String planNombre;
     private Integer planVigente;
     private Integer planActivo;
     private Date planFecha;
     private Integer planIngresoObligatorio;

    public Planes() {
    }

	
    public Planes(int carreraId) {
        this.carreraId = carreraId;
    }
    public Planes(int carreraId, String planNombre, Integer planVigente, Integer planActivo, Date planFecha, Integer planIngresoObligatorio) {
       this.carreraId = carreraId;
       this.planNombre = planNombre;
       this.planVigente = planVigente;
       this.planActivo = planActivo;
       this.planFecha = planFecha;
       this.planIngresoObligatorio = planIngresoObligatorio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="planId", unique=true, nullable=false)
    public Integer getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    
    @Column(name="carreraId", nullable=false)
    public int getCarreraId() {
        return this.carreraId;
    }
    
    public void setCarreraId(int carreraId) {
        this.carreraId = carreraId;
    }

    
    @Column(name="planNombre", length=60)
    public String getPlanNombre() {
        return this.planNombre;
    }
    
    public void setPlanNombre(String planNombre) {
        this.planNombre = planNombre;
    }

    
    @Column(name="planVigente")
    public Integer getPlanVigente() {
        return this.planVigente;
    }
    
    public void setPlanVigente(Integer planVigente) {
        this.planVigente = planVigente;
    }

    
    @Column(name="planActivo")
    public Integer getPlanActivo() {
        return this.planActivo;
    }
    
    public void setPlanActivo(Integer planActivo) {
        this.planActivo = planActivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="planFecha", length=10)
    public Date getPlanFecha() {
        return this.planFecha;
    }
    
    public void setPlanFecha(Date planFecha) {
        this.planFecha = planFecha;
    }

    
    @Column(name="planIngresoObligatorio")
    public Integer getPlanIngresoObligatorio() {
        return this.planIngresoObligatorio;
    }
    
    public void setPlanIngresoObligatorio(Integer planIngresoObligatorio) {
        this.planIngresoObligatorio = planIngresoObligatorio;
    }




}


