package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name="provincia"
    ,catalog="sgaundec"
)
public class Provincia  implements java.io.Serializable {


     private Integer provinciaId;
     private String provinciaNombre;
     private Integer paisId;

    public Provincia() {
    }

    public Provincia(String provinciaNombre, Integer paisId) {
       this.provinciaNombre = provinciaNombre;
       this.paisId = paisId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="provinciaId", unique=true, nullable=false)
    public Integer getProvinciaId() {
        return this.provinciaId;
    }
    
    public void setProvinciaId(Integer provinciaId) {
        this.provinciaId = provinciaId;
    }

    
    @Column(name="provinciaNombre", length=60)
    public String getProvinciaNombre() {
        return this.provinciaNombre;
    }
    
    public void setProvinciaNombre(String provinciaNombre) {
        this.provinciaNombre = provinciaNombre;
    }

    
    @Column(name="paisId")
    public Integer getPaisId() {
        return this.paisId;
    }
    
    public void setPaisId(Integer paisId) {
        this.paisId = paisId;
    }




}


