package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registro generated by hbm2java
 */
@Entity
@Table(name="registro"
    ,catalog="sgaundec"
)
public class Registro  implements java.io.Serializable {


     private Integer registroId;
     private Integer usuarioId;
     private Integer formularioId;
     private Integer tipoOperacionId;
     private String registroOperacion;
     private Date registroFecha;
     private Date registroHora;

    public Registro() {
    }

    public Registro(Integer usuarioId, Integer formularioId, Integer tipoOperacionId, String registroOperacion, Date registroFecha, Date registroHora) {
       this.usuarioId = usuarioId;
       this.formularioId = formularioId;
       this.tipoOperacionId = tipoOperacionId;
       this.registroOperacion = registroOperacion;
       this.registroFecha = registroFecha;
       this.registroHora = registroHora;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="registroId", unique=true, nullable=false)
    public Integer getRegistroId() {
        return this.registroId;
    }
    
    public void setRegistroId(Integer registroId) {
        this.registroId = registroId;
    }

    
    @Column(name="usuarioId")
    public Integer getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }

    
    @Column(name="formularioId")
    public Integer getFormularioId() {
        return this.formularioId;
    }
    
    public void setFormularioId(Integer formularioId) {
        this.formularioId = formularioId;
    }

    
    @Column(name="tipoOperacionId")
    public Integer getTipoOperacionId() {
        return this.tipoOperacionId;
    }
    
    public void setTipoOperacionId(Integer tipoOperacionId) {
        this.tipoOperacionId = tipoOperacionId;
    }

    
    @Column(name="registroOperacion", length=65535)
    public String getRegistroOperacion() {
        return this.registroOperacion;
    }
    
    public void setRegistroOperacion(String registroOperacion) {
        this.registroOperacion = registroOperacion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="registroFecha", length=10)
    public Date getRegistroFecha() {
        return this.registroFecha;
    }
    
    public void setRegistroFecha(Date registroFecha) {
        this.registroFecha = registroFecha;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="registroHora", length=8)
    public Date getRegistroHora() {
        return this.registroHora;
    }
    
    public void setRegistroHora(Date registroHora) {
        this.registroHora = registroHora;
    }




}


