package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Regularidad generated by hbm2java
 */
@Entity
@Table(name="regularidad"
    ,catalog="sgaundec"
)
public class Regularidad  implements java.io.Serializable {


     private Integer regularidadId;
     private int inscriptoId;
     private int actaRegularidadId;
     private Double regularidadAsistencia;
     private Integer regularidadNota;
     private Character regularidadCondicion;
     private Integer regularidadDuracion;

    public Regularidad() {
    }

	
    public Regularidad(int inscriptoId, int actaRegularidadId) {
        this.inscriptoId = inscriptoId;
        this.actaRegularidadId = actaRegularidadId;
    }
    public Regularidad(int inscriptoId, int actaRegularidadId, Double regularidadAsistencia, Integer regularidadNota, Character regularidadCondicion, Integer regularidadDuracion) {
       this.inscriptoId = inscriptoId;
       this.actaRegularidadId = actaRegularidadId;
       this.regularidadAsistencia = regularidadAsistencia;
       this.regularidadNota = regularidadNota;
       this.regularidadCondicion = regularidadCondicion;
       this.regularidadDuracion = regularidadDuracion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="regularidadId", unique=true, nullable=false)
    public Integer getRegularidadId() {
        return this.regularidadId;
    }
    
    public void setRegularidadId(Integer regularidadId) {
        this.regularidadId = regularidadId;
    }

    
    @Column(name="inscriptoId", nullable=false)
    public int getInscriptoId() {
        return this.inscriptoId;
    }
    
    public void setInscriptoId(int inscriptoId) {
        this.inscriptoId = inscriptoId;
    }

    
    @Column(name="actaRegularidadId", nullable=false)
    public int getActaRegularidadId() {
        return this.actaRegularidadId;
    }
    
    public void setActaRegularidadId(int actaRegularidadId) {
        this.actaRegularidadId = actaRegularidadId;
    }

    
    @Column(name="regularidadAsistencia", precision=22, scale=0)
    public Double getRegularidadAsistencia() {
        return this.regularidadAsistencia;
    }
    
    public void setRegularidadAsistencia(Double regularidadAsistencia) {
        this.regularidadAsistencia = regularidadAsistencia;
    }

    
    @Column(name="regularidadNota")
    public Integer getRegularidadNota() {
        return this.regularidadNota;
    }
    
    public void setRegularidadNota(Integer regularidadNota) {
        this.regularidadNota = regularidadNota;
    }

    
    @Column(name="regularidadCondicion", length=1)
    public Character getRegularidadCondicion() {
        return this.regularidadCondicion;
    }
    
    public void setRegularidadCondicion(Character regularidadCondicion) {
        this.regularidadCondicion = regularidadCondicion;
    }

    
    @Column(name="regularidadDuracion")
    public Integer getRegularidadDuracion() {
        return this.regularidadDuracion;
    }
    
    public void setRegularidadDuracion(Integer regularidadDuracion) {
        this.regularidadDuracion = regularidadDuracion;
    }




}


