package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Requisito generated by hbm2java
 */
@Entity
@Table(name="requisito"
    ,catalog="sgaundec"
)
public class Requisito  implements java.io.Serializable {


     private Integer requisitoId;
     private String requisitoDescripcion;

    public Requisito() {
    }

    public Requisito(String requisitoDescripcion) {
       this.requisitoDescripcion = requisitoDescripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="requisitoId", unique=true, nullable=false)
    public Integer getRequisitoId() {
        return this.requisitoId;
    }
    
    public void setRequisitoId(Integer requisitoId) {
        this.requisitoId = requisitoId;
    }

    
    @Column(name="requisitoDescripcion", length=150)
    public String getRequisitoDescripcion() {
        return this.requisitoDescripcion;
    }
    
    public void setRequisitoDescripcion(String requisitoDescripcion) {
        this.requisitoDescripcion = requisitoDescripcion;
    }




}


