package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Requisitociclo generated by hbm2java
 */
@Entity
@Table(name="requisitociclo"
    ,catalog="sgaundec"
)
public class Requisitociclo  implements java.io.Serializable {


     private RequisitocicloId id;
     private Integer requisitoCicloObligatorio;

    public Requisitociclo() {
    }

	
    public Requisitociclo(RequisitocicloId id) {
        this.id = id;
    }
    public Requisitociclo(RequisitocicloId id, Integer requisitoCicloObligatorio) {
       this.id = id;
       this.requisitoCicloObligatorio = requisitoCicloObligatorio;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="requisitoId", column=@Column(name="requisitoId", nullable=false) ), 
        @AttributeOverride(name="cicloAno", column=@Column(name="cicloAno", nullable=false) ) } )
    public RequisitocicloId getId() {
        return this.id;
    }
    
    public void setId(RequisitocicloId id) {
        this.id = id;
    }

    
    @Column(name="requisitoCicloObligatorio")
    public Integer getRequisitoCicloObligatorio() {
        return this.requisitoCicloObligatorio;
    }
    
    public void setRequisitoCicloObligatorio(Integer requisitoCicloObligatorio) {
        this.requisitoCicloObligatorio = requisitoCicloObligatorio;
    }




}


