package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Requisitoalumno generated by hbm2java
 */
@Entity
@Table(name="requisitoalumno"
    ,catalog="sgaundec"
)
public class Requisitoalumno  implements java.io.Serializable {


     private RequisitoalumnoId id;
     private Date requisitoAlumnoFecha;
     private String requisitoAlumnoObservacion;

    public Requisitoalumno() {
    }

	
    public Requisitoalumno(RequisitoalumnoId id) {
        this.id = id;
    }
    public Requisitoalumno(RequisitoalumnoId id, Date requisitoAlumnoFecha, String requisitoAlumnoObservacion) {
       this.id = id;
       this.requisitoAlumnoFecha = requisitoAlumnoFecha;
       this.requisitoAlumnoObservacion = requisitoAlumnoObservacion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="requisitoId", column=@Column(name="requisitoId", nullable=false) ), 
        @AttributeOverride(name="alumnoId", column=@Column(name="alumnoId", nullable=false) ) } )
    public RequisitoalumnoId getId() {
        return this.id;
    }
    
    public void setId(RequisitoalumnoId id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="requisitoAlumnoFecha", length=10)
    public Date getRequisitoAlumnoFecha() {
        return this.requisitoAlumnoFecha;
    }
    
    public void setRequisitoAlumnoFecha(Date requisitoAlumnoFecha) {
        this.requisitoAlumnoFecha = requisitoAlumnoFecha;
    }

    
    @Column(name="requisitoAlumnoObservacion", length=150)
    public String getRequisitoAlumnoObservacion() {
        return this.requisitoAlumnoObservacion;
    }
    
    public void setRequisitoAlumnoObservacion(String requisitoAlumnoObservacion) {
        this.requisitoAlumnoObservacion = requisitoAlumnoObservacion;
    }




}


