package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipomateria generated by hbm2java
 */
@Entity
@Table(name="tipomateria"
    ,catalog="sgaundec"
)
public class Tipomateria  implements java.io.Serializable {


     private Integer tipoMateriaId;
     private String tipoMateriaDescripcion;
     private Integer tipoMateriaSemanas;

    public Tipomateria() {
    }

    public Tipomateria(String tipoMateriaDescripcion, Integer tipoMateriaSemanas) {
       this.tipoMateriaDescripcion = tipoMateriaDescripcion;
       this.tipoMateriaSemanas = tipoMateriaSemanas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tipoMateriaId", unique=true, nullable=false)
    public Integer getTipoMateriaId() {
        return this.tipoMateriaId;
    }
    
    public void setTipoMateriaId(Integer tipoMateriaId) {
        this.tipoMateriaId = tipoMateriaId;
    }

    
    @Column(name="tipoMateriaDescripcion", length=60)
    public String getTipoMateriaDescripcion() {
        return this.tipoMateriaDescripcion;
    }
    
    public void setTipoMateriaDescripcion(String tipoMateriaDescripcion) {
        this.tipoMateriaDescripcion = tipoMateriaDescripcion;
    }

    
    @Column(name="tipoMateriaSemanas")
    public Integer getTipoMateriaSemanas() {
        return this.tipoMateriaSemanas;
    }
    
    public void setTipoMateriaSemanas(Integer tipoMateriaSemanas) {
        this.tipoMateriaSemanas = tipoMateriaSemanas;
    }




}


