package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tipooperacion generated by hbm2java
 */
@Entity
@Table(name="tipooperacion"
    ,catalog="sgaundec"
)
public class Tipooperacion  implements java.io.Serializable {


     private Integer tipoOperacionId;
     private String tipoOperacionNombre;

    public Tipooperacion() {
    }

    public Tipooperacion(String tipoOperacionNombre) {
       this.tipoOperacionNombre = tipoOperacionNombre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tipoOperacionId", unique=true, nullable=false)
    public Integer getTipoOperacionId() {
        return this.tipoOperacionId;
    }
    
    public void setTipoOperacionId(Integer tipoOperacionId) {
        this.tipoOperacionId = tipoOperacionId;
    }

    
    @Column(name="tipoOperacionNombre", length=200)
    public String getTipoOperacionNombre() {
        return this.tipoOperacionNombre;
    }
    
    public void setTipoOperacionNombre(String tipoOperacionNombre) {
        this.tipoOperacionNombre = tipoOperacionNombre;
    }




}


