package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Titulo generated by hbm2java
 */
@Entity
@Table(name="titulo"
    ,catalog="sgaundec"
)
public class Titulo  implements java.io.Serializable {


     private Integer tituloId;
     private String tituloNombre;

    public Titulo() {
    }

    public Titulo(String tituloNombre) {
       this.tituloNombre = tituloNombre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tituloId", unique=true, nullable=false)
    public Integer getTituloId() {
        return this.tituloId;
    }
    
    public void setTituloId(Integer tituloId) {
        this.tituloId = tituloId;
    }

    
    @Column(name="tituloNombre", length=250)
    public String getTituloNombre() {
        return this.tituloNombre;
    }
    
    public void setTituloNombre(String tituloNombre) {
        this.tituloNombre = tituloNombre;
    }




}


