package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Turnonombre generated by hbm2java
 */
@Entity
@Table(name="turnonombre"
    ,catalog="sgaundec"
)
public class Turnonombre  implements java.io.Serializable {


     private Integer turnoNombreId;
     private String turnoNombreDescripcion;
     private Integer turnoNombreLlamados;

    public Turnonombre() {
    }

    public Turnonombre(String turnoNombreDescripcion, Integer turnoNombreLlamados) {
       this.turnoNombreDescripcion = turnoNombreDescripcion;
       this.turnoNombreLlamados = turnoNombreLlamados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="turnoNombreId", unique=true, nullable=false)
    public Integer getTurnoNombreId() {
        return this.turnoNombreId;
    }
    
    public void setTurnoNombreId(Integer turnoNombreId) {
        this.turnoNombreId = turnoNombreId;
    }

    
    @Column(name="turnoNombreDescripcion", length=60)
    public String getTurnoNombreDescripcion() {
        return this.turnoNombreDescripcion;
    }
    
    public void setTurnoNombreDescripcion(String turnoNombreDescripcion) {
        this.turnoNombreDescripcion = turnoNombreDescripcion;
    }

    
    @Column(name="turnoNombreLlamados")
    public Integer getTurnoNombreLlamados() {
        return this.turnoNombreLlamados;
    }
    
    public void setTurnoNombreLlamados(Integer turnoNombreLlamados) {
        this.turnoNombreLlamados = turnoNombreLlamados;
    }




}


