package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioaccesoId generated by hbm2java
 */
@Embeddable
public class UsuarioaccesoId  implements java.io.Serializable {


     private int usuarioId;
     private int formularioId;

    public UsuarioaccesoId() {
    }

    public UsuarioaccesoId(int usuarioId, int formularioId) {
       this.usuarioId = usuarioId;
       this.formularioId = formularioId;
    }
   


    @Column(name="usuarioId", nullable=false)
    public int getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }


    @Column(name="formularioId", nullable=false)
    public int getFormularioId() {
        return this.formularioId;
    }
    
    public void setFormularioId(int formularioId) {
        this.formularioId = formularioId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioaccesoId) ) return false;
		 UsuarioaccesoId castOther = ( UsuarioaccesoId ) other; 
         
		 return (this.getUsuarioId()==castOther.getUsuarioId())
 && (this.getFormularioId()==castOther.getFormularioId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuarioId();
         result = 37 * result + this.getFormularioId();
         return result;
   }   


}


