package ar.com.pauen.modelo;
// Generated 21/02/2012 14:05:36 by Hibernate Tools 3.4.0.CR1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Usuarioacceso generated by hbm2java
 */
@Entity
@Table(name="usuarioacceso"
    ,catalog="sgaundec"
)
public class Usuarioacceso  implements java.io.Serializable {


     private UsuarioaccesoId id;
     private int usuarioAccesoConsulta;
     private int usuarioAccesoAgregar;
     private int usuarioAccesoModificar;
     private int usuarioAccesoEliminar;

    public Usuarioacceso() {
    }

    public Usuarioacceso(UsuarioaccesoId id, int usuarioAccesoConsulta, int usuarioAccesoAgregar, int usuarioAccesoModificar, int usuarioAccesoEliminar) {
       this.id = id;
       this.usuarioAccesoConsulta = usuarioAccesoConsulta;
       this.usuarioAccesoAgregar = usuarioAccesoAgregar;
       this.usuarioAccesoModificar = usuarioAccesoModificar;
       this.usuarioAccesoEliminar = usuarioAccesoEliminar;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="usuarioId", column=@Column(name="usuarioId", nullable=false) ), 
        @AttributeOverride(name="formularioId", column=@Column(name="formularioId", nullable=false) ) } )
    public UsuarioaccesoId getId() {
        return this.id;
    }
    
    public void setId(UsuarioaccesoId id) {
        this.id = id;
    }

    
    @Column(name="usuarioAccesoConsulta", nullable=false)
    public int getUsuarioAccesoConsulta() {
        return this.usuarioAccesoConsulta;
    }
    
    public void setUsuarioAccesoConsulta(int usuarioAccesoConsulta) {
        this.usuarioAccesoConsulta = usuarioAccesoConsulta;
    }

    
    @Column(name="usuarioAccesoAgregar", nullable=false)
    public int getUsuarioAccesoAgregar() {
        return this.usuarioAccesoAgregar;
    }
    
    public void setUsuarioAccesoAgregar(int usuarioAccesoAgregar) {
        this.usuarioAccesoAgregar = usuarioAccesoAgregar;
    }

    
    @Column(name="usuarioAccesoModificar", nullable=false)
    public int getUsuarioAccesoModificar() {
        return this.usuarioAccesoModificar;
    }
    
    public void setUsuarioAccesoModificar(int usuarioAccesoModificar) {
        this.usuarioAccesoModificar = usuarioAccesoModificar;
    }

    
    @Column(name="usuarioAccesoEliminar", nullable=false)
    public int getUsuarioAccesoEliminar() {
        return this.usuarioAccesoEliminar;
    }
    
    public void setUsuarioAccesoEliminar(int usuarioAccesoEliminar) {
        this.usuarioAccesoEliminar = usuarioAccesoEliminar;
    }




}


