package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Actafinal generated by hbm2java
 */
public class Actafinal  implements java.io.Serializable {


     private Integer actaFinalId;
     private int llamadoId;
     private int materiaId;
     private Integer actaFinalLibro;
     private Integer actaFinalNumero;
     private Date actaFinalFecha;
     private String actaFinalHora;
     private Date actaFinalLimiteInscripcion;
     private Date actaFinalFechaCierre;
     private int presidenteId;
     private int vocalId;
     private int suplenteId;
     private String actaFinalObservaciones;
     private String actaFinalEstado;

    public Actafinal() {
    }

	
    public Actafinal(int llamadoId, int materiaId, int presidenteId, int vocalId, int suplenteId) {
        this.llamadoId = llamadoId;
        this.materiaId = materiaId;
        this.presidenteId = presidenteId;
        this.vocalId = vocalId;
        this.suplenteId = suplenteId;
    }
    public Actafinal(int llamadoId, int materiaId, Integer actaFinalLibro, Integer actaFinalNumero, Date actaFinalFecha, String actaFinalHora, Date actaFinalLimiteInscripcion, Date actaFinalFechaCierre, int presidenteId, int vocalId, int suplenteId, String actaFinalObservaciones, String actaFinalEstado) {
       this.llamadoId = llamadoId;
       this.materiaId = materiaId;
       this.actaFinalLibro = actaFinalLibro;
       this.actaFinalNumero = actaFinalNumero;
       this.actaFinalFecha = actaFinalFecha;
       this.actaFinalHora = actaFinalHora;
       this.actaFinalLimiteInscripcion = actaFinalLimiteInscripcion;
       this.actaFinalFechaCierre = actaFinalFechaCierre;
       this.presidenteId = presidenteId;
       this.vocalId = vocalId;
       this.suplenteId = suplenteId;
       this.actaFinalObservaciones = actaFinalObservaciones;
       this.actaFinalEstado = actaFinalEstado;
    }
   
    public Integer getActaFinalId() {
        return this.actaFinalId;
    }
    
    public void setActaFinalId(Integer actaFinalId) {
        this.actaFinalId = actaFinalId;
    }
    public int getLlamadoId() {
        return this.llamadoId;
    }
    
    public void setLlamadoId(int llamadoId) {
        this.llamadoId = llamadoId;
    }
    public int getMateriaId() {
        return this.materiaId;
    }
    
    public void setMateriaId(int materiaId) {
        this.materiaId = materiaId;
    }
    public Integer getActaFinalLibro() {
        return this.actaFinalLibro;
    }
    
    public void setActaFinalLibro(Integer actaFinalLibro) {
        this.actaFinalLibro = actaFinalLibro;
    }
    public Integer getActaFinalNumero() {
        return this.actaFinalNumero;
    }
    
    public void setActaFinalNumero(Integer actaFinalNumero) {
        this.actaFinalNumero = actaFinalNumero;
    }
    public Date getActaFinalFecha() {
        return this.actaFinalFecha;
    }
    
    public void setActaFinalFecha(Date actaFinalFecha) {
        this.actaFinalFecha = actaFinalFecha;
    }
    public String getActaFinalHora() {
        return this.actaFinalHora;
    }
    
    public void setActaFinalHora(String actaFinalHora) {
        this.actaFinalHora = actaFinalHora;
    }
    public Date getActaFinalLimiteInscripcion() {
        return this.actaFinalLimiteInscripcion;
    }
    
    public void setActaFinalLimiteInscripcion(Date actaFinalLimiteInscripcion) {
        this.actaFinalLimiteInscripcion = actaFinalLimiteInscripcion;
    }
    public Date getActaFinalFechaCierre() {
        return this.actaFinalFechaCierre;
    }
    
    public void setActaFinalFechaCierre(Date actaFinalFechaCierre) {
        this.actaFinalFechaCierre = actaFinalFechaCierre;
    }
    public int getPresidenteId() {
        return this.presidenteId;
    }
    
    public void setPresidenteId(int presidenteId) {
        this.presidenteId = presidenteId;
    }
    public int getVocalId() {
        return this.vocalId;
    }
    
    public void setVocalId(int vocalId) {
        this.vocalId = vocalId;
    }
    public int getSuplenteId() {
        return this.suplenteId;
    }
    
    public void setSuplenteId(int suplenteId) {
        this.suplenteId = suplenteId;
    }
    public String getActaFinalObservaciones() {
        return this.actaFinalObservaciones;
    }
    
    public void setActaFinalObservaciones(String actaFinalObservaciones) {
        this.actaFinalObservaciones = actaFinalObservaciones;
    }
    public String getActaFinalEstado() {
        return this.actaFinalEstado;
    }
    
    public void setActaFinalEstado(String actaFinalEstado) {
        this.actaFinalEstado = actaFinalEstado;
    }




}


