package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Actaregularidad generated by hbm2java
 */
public class Actaregularidad  implements java.io.Serializable {


     private Integer actaRegularidadId;
     private int periodoId;
     private int materiaId;
     private Date actaRegularidadLimitePresentacion;
     private Date actaRegularidadFecha;
     private String actaRegularidadEstado;
     private String actaRegularidadObservaciones;

    public Actaregularidad() {
    }

	
    public Actaregularidad(int periodoId, int materiaId) {
        this.periodoId = periodoId;
        this.materiaId = materiaId;
    }
    public Actaregularidad(int periodoId, int materiaId, Date actaRegularidadLimitePresentacion, Date actaRegularidadFecha, String actaRegularidadEstado, String actaRegularidadObservaciones) {
       this.periodoId = periodoId;
       this.materiaId = materiaId;
       this.actaRegularidadLimitePresentacion = actaRegularidadLimitePresentacion;
       this.actaRegularidadFecha = actaRegularidadFecha;
       this.actaRegularidadEstado = actaRegularidadEstado;
       this.actaRegularidadObservaciones = actaRegularidadObservaciones;
    }
   
    public Integer getActaRegularidadId() {
        return this.actaRegularidadId;
    }
    
    public void setActaRegularidadId(Integer actaRegularidadId) {
        this.actaRegularidadId = actaRegularidadId;
    }
    public int getPeriodoId() {
        return this.periodoId;
    }
    
    public void setPeriodoId(int periodoId) {
        this.periodoId = periodoId;
    }
    public int getMateriaId() {
        return this.materiaId;
    }
    
    public void setMateriaId(int materiaId) {
        this.materiaId = materiaId;
    }
    public Date getActaRegularidadLimitePresentacion() {
        return this.actaRegularidadLimitePresentacion;
    }
    
    public void setActaRegularidadLimitePresentacion(Date actaRegularidadLimitePresentacion) {
        this.actaRegularidadLimitePresentacion = actaRegularidadLimitePresentacion;
    }
    public Date getActaRegularidadFecha() {
        return this.actaRegularidadFecha;
    }
    
    public void setActaRegularidadFecha(Date actaRegularidadFecha) {
        this.actaRegularidadFecha = actaRegularidadFecha;
    }
    public String getActaRegularidadEstado() {
        return this.actaRegularidadEstado;
    }
    
    public void setActaRegularidadEstado(String actaRegularidadEstado) {
        this.actaRegularidadEstado = actaRegularidadEstado;
    }
    public String getActaRegularidadObservaciones() {
        return this.actaRegularidadObservaciones;
    }
    
    public void setActaRegularidadObservaciones(String actaRegularidadObservaciones) {
        this.actaRegularidadObservaciones = actaRegularidadObservaciones;
    }




}


