package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer alumnoId;
     private int personaId;
     private Date alumnoFecha;
     private String alumnoMatricula;
     private Date alumnoFechaLibreta;
     private String alumnoOtrosEstudios;
     private Integer alumnoNivelOtrosEstudios;
     private Integer cicloAno;
     private Date alumnoFechaBaja;
     private Date alumnoFechaEgreso;

    public Alumno() {
    }

	
    public Alumno(int personaId) {
        this.personaId = personaId;
    }
    public Alumno(int personaId, Date alumnoFecha, String alumnoMatricula, Date alumnoFechaLibreta, String alumnoOtrosEstudios, Integer alumnoNivelOtrosEstudios, Integer cicloAno, Date alumnoFechaBaja, Date alumnoFechaEgreso) {
       this.personaId = personaId;
       this.alumnoFecha = alumnoFecha;
       this.alumnoMatricula = alumnoMatricula;
       this.alumnoFechaLibreta = alumnoFechaLibreta;
       this.alumnoOtrosEstudios = alumnoOtrosEstudios;
       this.alumnoNivelOtrosEstudios = alumnoNivelOtrosEstudios;
       this.cicloAno = cicloAno;
       this.alumnoFechaBaja = alumnoFechaBaja;
       this.alumnoFechaEgreso = alumnoFechaEgreso;
    }
   
    public Integer getAlumnoId() {
        return this.alumnoId;
    }
    
    public void setAlumnoId(Integer alumnoId) {
        this.alumnoId = alumnoId;
    }
    public int getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(int personaId) {
        this.personaId = personaId;
    }
    public Date getAlumnoFecha() {
        return this.alumnoFecha;
    }
    
    public void setAlumnoFecha(Date alumnoFecha) {
        this.alumnoFecha = alumnoFecha;
    }
    public String getAlumnoMatricula() {
        return this.alumnoMatricula;
    }
    
    public void setAlumnoMatricula(String alumnoMatricula) {
        this.alumnoMatricula = alumnoMatricula;
    }
    public Date getAlumnoFechaLibreta() {
        return this.alumnoFechaLibreta;
    }
    
    public void setAlumnoFechaLibreta(Date alumnoFechaLibreta) {
        this.alumnoFechaLibreta = alumnoFechaLibreta;
    }
    public String getAlumnoOtrosEstudios() {
        return this.alumnoOtrosEstudios;
    }
    
    public void setAlumnoOtrosEstudios(String alumnoOtrosEstudios) {
        this.alumnoOtrosEstudios = alumnoOtrosEstudios;
    }
    public Integer getAlumnoNivelOtrosEstudios() {
        return this.alumnoNivelOtrosEstudios;
    }
    
    public void setAlumnoNivelOtrosEstudios(Integer alumnoNivelOtrosEstudios) {
        this.alumnoNivelOtrosEstudios = alumnoNivelOtrosEstudios;
    }
    public Integer getCicloAno() {
        return this.cicloAno;
    }
    
    public void setCicloAno(Integer cicloAno) {
        this.cicloAno = cicloAno;
    }
    public Date getAlumnoFechaBaja() {
        return this.alumnoFechaBaja;
    }
    
    public void setAlumnoFechaBaja(Date alumnoFechaBaja) {
        this.alumnoFechaBaja = alumnoFechaBaja;
    }
    public Date getAlumnoFechaEgreso() {
        return this.alumnoFechaEgreso;
    }
    
    public void setAlumnoFechaEgreso(Date alumnoFechaEgreso) {
        this.alumnoFechaEgreso = alumnoFechaEgreso;
    }




}


