package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private Integer carreraId;
     private String carreraNombre;
     private Integer carreraMatriculaInicial;

    public Carrera() {
    }

    public Carrera(String carreraNombre, Integer carreraMatriculaInicial) {
       this.carreraNombre = carreraNombre;
       this.carreraMatriculaInicial = carreraMatriculaInicial;
    }
   
    public Integer getCarreraId() {
        return this.carreraId;
    }
    
    public void setCarreraId(Integer carreraId) {
        this.carreraId = carreraId;
    }
    public String getCarreraNombre() {
        return this.carreraNombre;
    }
    
    public void setCarreraNombre(String carreraNombre) {
        this.carreraNombre = carreraNombre;
    }
    public Integer getCarreraMatriculaInicial() {
        return this.carreraMatriculaInicial;
    }
    
    public void setCarreraMatriculaInicial(Integer carreraMatriculaInicial) {
        this.carreraMatriculaInicial = carreraMatriculaInicial;
    }




}


