package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Ciclo generated by hbm2java
 */
public class Ciclo  implements java.io.Serializable {


     private Integer cicloAno;
     private Date cicloFechaInicio;
     private Date cicloFechaFin;

    public Ciclo() {
    }

    public Ciclo(Date cicloFechaInicio, Date cicloFechaFin) {
       this.cicloFechaInicio = cicloFechaInicio;
       this.cicloFechaFin = cicloFechaFin;
    }
   
    public Integer getCicloAno() {
        return this.cicloAno;
    }
    
    public void setCicloAno(Integer cicloAno) {
        this.cicloAno = cicloAno;
    }
    public Date getCicloFechaInicio() {
        return this.cicloFechaInicio;
    }
    
    public void setCicloFechaInicio(Date cicloFechaInicio) {
        this.cicloFechaInicio = cicloFechaInicio;
    }
    public Date getCicloFechaFin() {
        return this.cicloFechaFin;
    }
    
    public void setCicloFechaFin(Date cicloFechaFin) {
        this.cicloFechaFin = cicloFechaFin;
    }




}


