package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Cursada generated by hbm2java
 */
public class Cursada  implements java.io.Serializable {


     private CursadaId id;
     private int actaRegularidadId;
     private Integer cursadaRecursa;

    public Cursada() {
    }

	
    public Cursada(CursadaId id, int actaRegularidadId) {
        this.id = id;
        this.actaRegularidadId = actaRegularidadId;
    }
    public Cursada(CursadaId id, int actaRegularidadId, Integer cursadaRecursa) {
       this.id = id;
       this.actaRegularidadId = actaRegularidadId;
       this.cursadaRecursa = cursadaRecursa;
    }
   
    public CursadaId getId() {
        return this.id;
    }
    
    public void setId(CursadaId id) {
        this.id = id;
    }
    public int getActaRegularidadId() {
        return this.actaRegularidadId;
    }
    
    public void setActaRegularidadId(int actaRegularidadId) {
        this.actaRegularidadId = actaRegularidadId;
    }
    public Integer getCursadaRecursa() {
        return this.cursadaRecursa;
    }
    
    public void setCursadaRecursa(Integer cursadaRecursa) {
        this.cursadaRecursa = cursadaRecursa;
    }




}


