package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * CursadaId generated by hbm2java
 */
public class CursadaId  implements java.io.Serializable {


     private int materiaId;
     private int inscripcionId;

    public CursadaId() {
    }

    public CursadaId(int materiaId, int inscripcionId) {
       this.materiaId = materiaId;
       this.inscripcionId = inscripcionId;
    }
   
    public int getMateriaId() {
        return this.materiaId;
    }
    
    public void setMateriaId(int materiaId) {
        this.materiaId = materiaId;
    }
    public int getInscripcionId() {
        return this.inscripcionId;
    }
    
    public void setInscripcionId(int inscripcionId) {
        this.inscripcionId = inscripcionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CursadaId) ) return false;
		 CursadaId castOther = ( CursadaId ) other; 
         
		 return (this.getMateriaId()==castOther.getMateriaId())
 && (this.getInscripcionId()==castOther.getInscripcionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMateriaId();
         result = 37 * result + this.getInscripcionId();
         return result;
   }   


}


