package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer departamentoId;
     private String departamentoNombre;
     private Integer provinciaId;

    public Departamento() {
    }

    public Departamento(String departamentoNombre, Integer provinciaId) {
       this.departamentoNombre = departamentoNombre;
       this.provinciaId = provinciaId;
    }
   
    public Integer getDepartamentoId() {
        return this.departamentoId;
    }
    
    public void setDepartamentoId(Integer departamentoId) {
        this.departamentoId = departamentoId;
    }
    public String getDepartamentoNombre() {
        return this.departamentoNombre;
    }
    
    public void setDepartamentoNombre(String departamentoNombre) {
        this.departamentoNombre = departamentoNombre;
    }
    public Integer getProvinciaId() {
        return this.provinciaId;
    }
    
    public void setProvinciaId(Integer provinciaId) {
        this.provinciaId = provinciaId;
    }




}


