package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Distrito generated by hbm2java
 */
public class Distrito  implements java.io.Serializable {


     private Integer distritoId;
     private String distritoNombre;
     private int departamentoId;

    public Distrito() {
    }

	
    public Distrito(int departamentoId) {
        this.departamentoId = departamentoId;
    }
    public Distrito(String distritoNombre, int departamentoId) {
       this.distritoNombre = distritoNombre;
       this.departamentoId = departamentoId;
    }
   
    public Integer getDistritoId() {
        return this.distritoId;
    }
    
    public void setDistritoId(Integer distritoId) {
        this.distritoId = distritoId;
    }
    public String getDistritoNombre() {
        return this.distritoNombre;
    }
    
    public void setDistritoNombre(String distritoNombre) {
        this.distritoNombre = distritoNombre;
    }
    public int getDepartamentoId() {
        return this.departamentoId;
    }
    
    public void setDepartamentoId(int departamentoId) {
        this.departamentoId = departamentoId;
    }




}


