package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private Integer docenteId;
     private String docenteTitulo;
     private String docenteNombre;
     private String docenteApellido;
     private String docenteTelefono;
     private String docenteEmail;
     private String docenteObservaciones;

    public Docente() {
    }

	
    public Docente(String docenteTitulo, String docenteNombre, String docenteApellido) {
        this.docenteTitulo = docenteTitulo;
        this.docenteNombre = docenteNombre;
        this.docenteApellido = docenteApellido;
    }
    public Docente(String docenteTitulo, String docenteNombre, String docenteApellido, String docenteTelefono, String docenteEmail, String docenteObservaciones) {
       this.docenteTitulo = docenteTitulo;
       this.docenteNombre = docenteNombre;
       this.docenteApellido = docenteApellido;
       this.docenteTelefono = docenteTelefono;
       this.docenteEmail = docenteEmail;
       this.docenteObservaciones = docenteObservaciones;
    }
   
    public Integer getDocenteId() {
        return this.docenteId;
    }
    
    public void setDocenteId(Integer docenteId) {
        this.docenteId = docenteId;
    }
    public String getDocenteTitulo() {
        return this.docenteTitulo;
    }
    
    public void setDocenteTitulo(String docenteTitulo) {
        this.docenteTitulo = docenteTitulo;
    }
    public String getDocenteNombre() {
        return this.docenteNombre;
    }
    
    public void setDocenteNombre(String docenteNombre) {
        this.docenteNombre = docenteNombre;
    }
    public String getDocenteApellido() {
        return this.docenteApellido;
    }
    
    public void setDocenteApellido(String docenteApellido) {
        this.docenteApellido = docenteApellido;
    }
    public String getDocenteTelefono() {
        return this.docenteTelefono;
    }
    
    public void setDocenteTelefono(String docenteTelefono) {
        this.docenteTelefono = docenteTelefono;
    }
    public String getDocenteEmail() {
        return this.docenteEmail;
    }
    
    public void setDocenteEmail(String docenteEmail) {
        this.docenteEmail = docenteEmail;
    }
    public String getDocenteObservaciones() {
        return this.docenteObservaciones;
    }
    
    public void setDocenteObservaciones(String docenteObservaciones) {
        this.docenteObservaciones = docenteObservaciones;
    }




}


