package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Domicilio generated by hbm2java
 */
public class Domicilio  implements java.io.Serializable {


     private Integer domicilioId;
     private int distritoId;
     private Integer personaId;
     private Integer domicilioTipo;
     private String domicilioCalle;
     private String domicilioNumero;
     private String domicilioBarrio;
     private String domicilioTelefono;
     private Date domicilioFecha;

    public Domicilio() {
    }

	
    public Domicilio(int distritoId) {
        this.distritoId = distritoId;
    }
    public Domicilio(int distritoId, Integer personaId, Integer domicilioTipo, String domicilioCalle, String domicilioNumero, String domicilioBarrio, String domicilioTelefono, Date domicilioFecha) {
       this.distritoId = distritoId;
       this.personaId = personaId;
       this.domicilioTipo = domicilioTipo;
       this.domicilioCalle = domicilioCalle;
       this.domicilioNumero = domicilioNumero;
       this.domicilioBarrio = domicilioBarrio;
       this.domicilioTelefono = domicilioTelefono;
       this.domicilioFecha = domicilioFecha;
    }
   
    public Integer getDomicilioId() {
        return this.domicilioId;
    }
    
    public void setDomicilioId(Integer domicilioId) {
        this.domicilioId = domicilioId;
    }
    public int getDistritoId() {
        return this.distritoId;
    }
    
    public void setDistritoId(int distritoId) {
        this.distritoId = distritoId;
    }
    public Integer getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(Integer personaId) {
        this.personaId = personaId;
    }
    public Integer getDomicilioTipo() {
        return this.domicilioTipo;
    }
    
    public void setDomicilioTipo(Integer domicilioTipo) {
        this.domicilioTipo = domicilioTipo;
    }
    public String getDomicilioCalle() {
        return this.domicilioCalle;
    }
    
    public void setDomicilioCalle(String domicilioCalle) {
        this.domicilioCalle = domicilioCalle;
    }
    public String getDomicilioNumero() {
        return this.domicilioNumero;
    }
    
    public void setDomicilioNumero(String domicilioNumero) {
        this.domicilioNumero = domicilioNumero;
    }
    public String getDomicilioBarrio() {
        return this.domicilioBarrio;
    }
    
    public void setDomicilioBarrio(String domicilioBarrio) {
        this.domicilioBarrio = domicilioBarrio;
    }
    public String getDomicilioTelefono() {
        return this.domicilioTelefono;
    }
    
    public void setDomicilioTelefono(String domicilioTelefono) {
        this.domicilioTelefono = domicilioTelefono;
    }
    public Date getDomicilioFecha() {
        return this.domicilioFecha;
    }
    
    public void setDomicilioFecha(Date domicilioFecha) {
        this.domicilioFecha = domicilioFecha;
    }




}


