package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Egresosecundario generated by hbm2java
 */
public class Egresosecundario  implements java.io.Serializable {


     private int personaId;
     private int escuelaId;
     private int tituloId;
     private Integer egresoSecundarioAno;

    public Egresosecundario() {
    }

	
    public Egresosecundario(int personaId, int escuelaId, int tituloId) {
        this.personaId = personaId;
        this.escuelaId = escuelaId;
        this.tituloId = tituloId;
    }
    public Egresosecundario(int personaId, int escuelaId, int tituloId, Integer egresoSecundarioAno) {
       this.personaId = personaId;
       this.escuelaId = escuelaId;
       this.tituloId = tituloId;
       this.egresoSecundarioAno = egresoSecundarioAno;
    }
   
    public int getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(int personaId) {
        this.personaId = personaId;
    }
    public int getEscuelaId() {
        return this.escuelaId;
    }
    
    public void setEscuelaId(int escuelaId) {
        this.escuelaId = escuelaId;
    }
    public int getTituloId() {
        return this.tituloId;
    }
    
    public void setTituloId(int tituloId) {
        this.tituloId = tituloId;
    }
    public Integer getEgresoSecundarioAno() {
        return this.egresoSecundarioAno;
    }
    
    public void setEgresoSecundarioAno(Integer egresoSecundarioAno) {
        this.egresoSecundarioAno = egresoSecundarioAno;
    }




}


