package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * EncuestaId generated by hbm2java
 */
public class EncuestaId  implements java.io.Serializable {


     private int encuestaId;
     private int inscripcionId;

    public EncuestaId() {
    }

    public EncuestaId(int encuestaId, int inscripcionId) {
       this.encuestaId = encuestaId;
       this.inscripcionId = inscripcionId;
    }
   
    public int getEncuestaId() {
        return this.encuestaId;
    }
    
    public void setEncuestaId(int encuestaId) {
        this.encuestaId = encuestaId;
    }
    public int getInscripcionId() {
        return this.inscripcionId;
    }
    
    public void setInscripcionId(int inscripcionId) {
        this.inscripcionId = inscripcionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EncuestaId) ) return false;
		 EncuestaId castOther = ( EncuestaId ) other; 
         
		 return (this.getEncuestaId()==castOther.getEncuestaId())
 && (this.getInscripcionId()==castOther.getInscripcionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getEncuestaId();
         result = 37 * result + this.getInscripcionId();
         return result;
   }   


}


