package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Escuelatipo generated by hbm2java
 */
public class Escuelatipo  implements java.io.Serializable {


     private Integer escuelaTipoId;
     private String escuelaTipoDescripcion;

    public Escuelatipo() {
    }

    public Escuelatipo(String escuelaTipoDescripcion) {
       this.escuelaTipoDescripcion = escuelaTipoDescripcion;
    }
   
    public Integer getEscuelaTipoId() {
        return this.escuelaTipoId;
    }
    
    public void setEscuelaTipoId(Integer escuelaTipoId) {
        this.escuelaTipoId = escuelaTipoId;
    }
    public String getEscuelaTipoDescripcion() {
        return this.escuelaTipoDescripcion;
    }
    
    public void setEscuelaTipoDescripcion(String escuelaTipoDescripcion) {
        this.escuelaTipoDescripcion = escuelaTipoDescripcion;
    }




}


