package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Escuela generated by hbm2java
 */
public class Escuela  implements java.io.Serializable {


     private Integer escuelaId;
     private String escuelaNombre;
     private Integer distritoId;
     private Integer escuelaTipoId;

    public Escuela() {
    }

    public Escuela(String escuelaNombre, Integer distritoId, Integer escuelaTipoId) {
       this.escuelaNombre = escuelaNombre;
       this.distritoId = distritoId;
       this.escuelaTipoId = escuelaTipoId;
    }
   
    public Integer getEscuelaId() {
        return this.escuelaId;
    }
    
    public void setEscuelaId(Integer escuelaId) {
        this.escuelaId = escuelaId;
    }
    public String getEscuelaNombre() {
        return this.escuelaNombre;
    }
    
    public void setEscuelaNombre(String escuelaNombre) {
        this.escuelaNombre = escuelaNombre;
    }
    public Integer getDistritoId() {
        return this.distritoId;
    }
    
    public void setDistritoId(Integer distritoId) {
        this.distritoId = distritoId;
    }
    public Integer getEscuelaTipoId() {
        return this.escuelaTipoId;
    }
    
    public void setEscuelaTipoId(Integer escuelaTipoId) {
        this.escuelaTipoId = escuelaTipoId;
    }




}


