package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Expedientedenominacion generated by hbm2java
 */
public class Expedientedenominacion  implements java.io.Serializable {


     private Integer expedienteDenominacionId;
     private String expedienteDenominacionNombre;

    public Expedientedenominacion() {
    }

    public Expedientedenominacion(String expedienteDenominacionNombre) {
       this.expedienteDenominacionNombre = expedienteDenominacionNombre;
    }
   
    public Integer getExpedienteDenominacionId() {
        return this.expedienteDenominacionId;
    }
    
    public void setExpedienteDenominacionId(Integer expedienteDenominacionId) {
        this.expedienteDenominacionId = expedienteDenominacionId;
    }
    public String getExpedienteDenominacionNombre() {
        return this.expedienteDenominacionNombre;
    }
    
    public void setExpedienteDenominacionNombre(String expedienteDenominacionNombre) {
        this.expedienteDenominacionNombre = expedienteDenominacionNombre;
    }




}


