package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Expedientetipo generated by hbm2java
 */
public class Expedientetipo  implements java.io.Serializable {


     private Integer expedienteTipoId;
     private String expedienteTipoDescripcion;

    public Expedientetipo() {
    }

    public Expedientetipo(String expedienteTipoDescripcion) {
       this.expedienteTipoDescripcion = expedienteTipoDescripcion;
    }
   
    public Integer getExpedienteTipoId() {
        return this.expedienteTipoId;
    }
    
    public void setExpedienteTipoId(Integer expedienteTipoId) {
        this.expedienteTipoId = expedienteTipoId;
    }
    public String getExpedienteTipoDescripcion() {
        return this.expedienteTipoDescripcion;
    }
    
    public void setExpedienteTipoDescripcion(String expedienteTipoDescripcion) {
        this.expedienteTipoDescripcion = expedienteTipoDescripcion;
    }




}


