package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Final generated by hbm2java
 */
public class Final  implements java.io.Serializable {


     private Integer finalId;
     private int inscriptoId;
     private int actaFinalId;
     private Character finalCondicion;
     private Integer finalNota;
     private int finalAusente;

    public Final() {
    }

	
    public Final(int inscriptoId, int actaFinalId, int finalAusente) {
        this.inscriptoId = inscriptoId;
        this.actaFinalId = actaFinalId;
        this.finalAusente = finalAusente;
    }
    public Final(int inscriptoId, int actaFinalId, Character finalCondicion, Integer finalNota, int finalAusente) {
       this.inscriptoId = inscriptoId;
       this.actaFinalId = actaFinalId;
       this.finalCondicion = finalCondicion;
       this.finalNota = finalNota;
       this.finalAusente = finalAusente;
    }
   
    public Integer getFinalId() {
        return this.finalId;
    }
    
    public void setFinalId(Integer finalId) {
        this.finalId = finalId;
    }
    public int getInscriptoId() {
        return this.inscriptoId;
    }
    
    public void setInscriptoId(int inscriptoId) {
        this.inscriptoId = inscriptoId;
    }
    public int getActaFinalId() {
        return this.actaFinalId;
    }
    
    public void setActaFinalId(int actaFinalId) {
        this.actaFinalId = actaFinalId;
    }
    public Character getFinalCondicion() {
        return this.finalCondicion;
    }
    
    public void setFinalCondicion(Character finalCondicion) {
        this.finalCondicion = finalCondicion;
    }
    public Integer getFinalNota() {
        return this.finalNota;
    }
    
    public void setFinalNota(Integer finalNota) {
        this.finalNota = finalNota;
    }
    public int getFinalAusente() {
        return this.finalAusente;
    }
    
    public void setFinalAusente(int finalAusente) {
        this.finalAusente = finalAusente;
    }




}


