package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Formulario generated by hbm2java
 */
public class Formulario  implements java.io.Serializable {


     private Integer formularioId;
     private String formularioNombre;
     private String formularioDescripcion;
     private String formularioMenu;
     private Integer formularioAccesoDefecto;

    public Formulario() {
    }

    public Formulario(String formularioNombre, String formularioDescripcion, String formularioMenu, Integer formularioAccesoDefecto) {
       this.formularioNombre = formularioNombre;
       this.formularioDescripcion = formularioDescripcion;
       this.formularioMenu = formularioMenu;
       this.formularioAccesoDefecto = formularioAccesoDefecto;
    }
   
    public Integer getFormularioId() {
        return this.formularioId;
    }
    
    public void setFormularioId(Integer formularioId) {
        this.formularioId = formularioId;
    }
    public String getFormularioNombre() {
        return this.formularioNombre;
    }
    
    public void setFormularioNombre(String formularioNombre) {
        this.formularioNombre = formularioNombre;
    }
    public String getFormularioDescripcion() {
        return this.formularioDescripcion;
    }
    
    public void setFormularioDescripcion(String formularioDescripcion) {
        this.formularioDescripcion = formularioDescripcion;
    }
    public String getFormularioMenu() {
        return this.formularioMenu;
    }
    
    public void setFormularioMenu(String formularioMenu) {
        this.formularioMenu = formularioMenu;
    }
    public Integer getFormularioAccesoDefecto() {
        return this.formularioAccesoDefecto;
    }
    
    public void setFormularioAccesoDefecto(Integer formularioAccesoDefecto) {
        this.formularioAccesoDefecto = formularioAccesoDefecto;
    }




}


