package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Ingresoaprobacion generated by hbm2java
 */
public class Ingresoaprobacion  implements java.io.Serializable {


     private Integer ingresoAprobacionId;
     private int inscriptoId;
     private int actaIngresoId;
     private Double ingresoAprobacionAsistencia;
     private Integer ingresoAprobacionNota;
     private Character ingresoAprobacionCondicion;

    public Ingresoaprobacion() {
    }

	
    public Ingresoaprobacion(int inscriptoId, int actaIngresoId) {
        this.inscriptoId = inscriptoId;
        this.actaIngresoId = actaIngresoId;
    }
    public Ingresoaprobacion(int inscriptoId, int actaIngresoId, Double ingresoAprobacionAsistencia, Integer ingresoAprobacionNota, Character ingresoAprobacionCondicion) {
       this.inscriptoId = inscriptoId;
       this.actaIngresoId = actaIngresoId;
       this.ingresoAprobacionAsistencia = ingresoAprobacionAsistencia;
       this.ingresoAprobacionNota = ingresoAprobacionNota;
       this.ingresoAprobacionCondicion = ingresoAprobacionCondicion;
    }
   
    public Integer getIngresoAprobacionId() {
        return this.ingresoAprobacionId;
    }
    
    public void setIngresoAprobacionId(Integer ingresoAprobacionId) {
        this.ingresoAprobacionId = ingresoAprobacionId;
    }
    public int getInscriptoId() {
        return this.inscriptoId;
    }
    
    public void setInscriptoId(int inscriptoId) {
        this.inscriptoId = inscriptoId;
    }
    public int getActaIngresoId() {
        return this.actaIngresoId;
    }
    
    public void setActaIngresoId(int actaIngresoId) {
        this.actaIngresoId = actaIngresoId;
    }
    public Double getIngresoAprobacionAsistencia() {
        return this.ingresoAprobacionAsistencia;
    }
    
    public void setIngresoAprobacionAsistencia(Double ingresoAprobacionAsistencia) {
        this.ingresoAprobacionAsistencia = ingresoAprobacionAsistencia;
    }
    public Integer getIngresoAprobacionNota() {
        return this.ingresoAprobacionNota;
    }
    
    public void setIngresoAprobacionNota(Integer ingresoAprobacionNota) {
        this.ingresoAprobacionNota = ingresoAprobacionNota;
    }
    public Character getIngresoAprobacionCondicion() {
        return this.ingresoAprobacionCondicion;
    }
    
    public void setIngresoAprobacionCondicion(Character ingresoAprobacionCondicion) {
        this.ingresoAprobacionCondicion = ingresoAprobacionCondicion;
    }




}


