package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Inscripcion generated by hbm2java
 */
public class Inscripcion  implements java.io.Serializable {


     private Integer inscripcionId;
     private int inscriptoId;
     private int cicloAno;
     private Integer tipoInscripcionId;
     private Date inscripcionFecha;
     private String inscripcionObservaciones;

    public Inscripcion() {
    }

	
    public Inscripcion(int inscriptoId, int cicloAno) {
        this.inscriptoId = inscriptoId;
        this.cicloAno = cicloAno;
    }
    public Inscripcion(int inscriptoId, int cicloAno, Integer tipoInscripcionId, Date inscripcionFecha, String inscripcionObservaciones) {
       this.inscriptoId = inscriptoId;
       this.cicloAno = cicloAno;
       this.tipoInscripcionId = tipoInscripcionId;
       this.inscripcionFecha = inscripcionFecha;
       this.inscripcionObservaciones = inscripcionObservaciones;
    }
   
    public Integer getInscripcionId() {
        return this.inscripcionId;
    }
    
    public void setInscripcionId(Integer inscripcionId) {
        this.inscripcionId = inscripcionId;
    }
    public int getInscriptoId() {
        return this.inscriptoId;
    }
    
    public void setInscriptoId(int inscriptoId) {
        this.inscriptoId = inscriptoId;
    }
    public int getCicloAno() {
        return this.cicloAno;
    }
    
    public void setCicloAno(int cicloAno) {
        this.cicloAno = cicloAno;
    }
    public Integer getTipoInscripcionId() {
        return this.tipoInscripcionId;
    }
    
    public void setTipoInscripcionId(Integer tipoInscripcionId) {
        this.tipoInscripcionId = tipoInscripcionId;
    }
    public Date getInscripcionFecha() {
        return this.inscripcionFecha;
    }
    
    public void setInscripcionFecha(Date inscripcionFecha) {
        this.inscripcionFecha = inscripcionFecha;
    }
    public String getInscripcionObservaciones() {
        return this.inscripcionObservaciones;
    }
    
    public void setInscripcionObservaciones(String inscripcionObservaciones) {
        this.inscripcionObservaciones = inscripcionObservaciones;
    }




}


