package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Inscripto generated by hbm2java
 */
public class Inscripto  implements java.io.Serializable {


     private Integer inscriptoId;
     private int planId;
     private int alumnoId;
     private Date inscriptoFecha;

    public Inscripto() {
    }

	
    public Inscripto(int planId, int alumnoId) {
        this.planId = planId;
        this.alumnoId = alumnoId;
    }
    public Inscripto(int planId, int alumnoId, Date inscriptoFecha) {
       this.planId = planId;
       this.alumnoId = alumnoId;
       this.inscriptoFecha = inscriptoFecha;
    }
   
    public Integer getInscriptoId() {
        return this.inscriptoId;
    }
    
    public void setInscriptoId(Integer inscriptoId) {
        this.inscriptoId = inscriptoId;
    }
    public int getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(int planId) {
        this.planId = planId;
    }
    public int getAlumnoId() {
        return this.alumnoId;
    }
    
    public void setAlumnoId(int alumnoId) {
        this.alumnoId = alumnoId;
    }
    public Date getInscriptoFecha() {
        return this.inscriptoFecha;
    }
    
    public void setInscriptoFecha(Date inscriptoFecha) {
        this.inscriptoFecha = inscriptoFecha;
    }




}


