package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Inscripcionfinal generated by hbm2java
 */
public class Inscripcionfinal  implements java.io.Serializable {


     private InscripcionfinalId id;

    public Inscripcionfinal() {
    }

    public Inscripcionfinal(InscripcionfinalId id) {
       this.id = id;
    }
   
    public InscripcionfinalId getId() {
        return this.id;
    }
    
    public void setId(InscripcionfinalId id) {
        this.id = id;
    }




}


