package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Inscripcionperiodo generated by hbm2java
 */
public class Inscripcionperiodo  implements java.io.Serializable {


     private Integer inscripcionPeriodoId;
     private int tipoInscripcionId;
     private int cicloAno;
     private Date inscripcionPeriodoDesde;
     private Date inscripcionPeriodoHasta;

    public Inscripcionperiodo() {
    }

	
    public Inscripcionperiodo(int tipoInscripcionId, int cicloAno) {
        this.tipoInscripcionId = tipoInscripcionId;
        this.cicloAno = cicloAno;
    }
    public Inscripcionperiodo(int tipoInscripcionId, int cicloAno, Date inscripcionPeriodoDesde, Date inscripcionPeriodoHasta) {
       this.tipoInscripcionId = tipoInscripcionId;
       this.cicloAno = cicloAno;
       this.inscripcionPeriodoDesde = inscripcionPeriodoDesde;
       this.inscripcionPeriodoHasta = inscripcionPeriodoHasta;
    }
   
    public Integer getInscripcionPeriodoId() {
        return this.inscripcionPeriodoId;
    }
    
    public void setInscripcionPeriodoId(Integer inscripcionPeriodoId) {
        this.inscripcionPeriodoId = inscripcionPeriodoId;
    }
    public int getTipoInscripcionId() {
        return this.tipoInscripcionId;
    }
    
    public void setTipoInscripcionId(int tipoInscripcionId) {
        this.tipoInscripcionId = tipoInscripcionId;
    }
    public int getCicloAno() {
        return this.cicloAno;
    }
    
    public void setCicloAno(int cicloAno) {
        this.cicloAno = cicloAno;
    }
    public Date getInscripcionPeriodoDesde() {
        return this.inscripcionPeriodoDesde;
    }
    
    public void setInscripcionPeriodoDesde(Date inscripcionPeriodoDesde) {
        this.inscripcionPeriodoDesde = inscripcionPeriodoDesde;
    }
    public Date getInscripcionPeriodoHasta() {
        return this.inscripcionPeriodoHasta;
    }
    
    public void setInscripcionPeriodoHasta(Date inscripcionPeriodoHasta) {
        this.inscripcionPeriodoHasta = inscripcionPeriodoHasta;
    }




}


