package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Llamado generated by hbm2java
 */
public class Llamado  implements java.io.Serializable {


     private Integer llamadoId;
     private int turnoId;
     private Integer llamadoNumero;
     private Date llamadoDesde;
     private Date llamadoHasta;

    public Llamado() {
    }

	
    public Llamado(int turnoId) {
        this.turnoId = turnoId;
    }
    public Llamado(int turnoId, Integer llamadoNumero, Date llamadoDesde, Date llamadoHasta) {
       this.turnoId = turnoId;
       this.llamadoNumero = llamadoNumero;
       this.llamadoDesde = llamadoDesde;
       this.llamadoHasta = llamadoHasta;
    }
   
    public Integer getLlamadoId() {
        return this.llamadoId;
    }
    
    public void setLlamadoId(Integer llamadoId) {
        this.llamadoId = llamadoId;
    }
    public int getTurnoId() {
        return this.turnoId;
    }
    
    public void setTurnoId(int turnoId) {
        this.turnoId = turnoId;
    }
    public Integer getLlamadoNumero() {
        return this.llamadoNumero;
    }
    
    public void setLlamadoNumero(Integer llamadoNumero) {
        this.llamadoNumero = llamadoNumero;
    }
    public Date getLlamadoDesde() {
        return this.llamadoDesde;
    }
    
    public void setLlamadoDesde(Date llamadoDesde) {
        this.llamadoDesde = llamadoDesde;
    }
    public Date getLlamadoHasta() {
        return this.llamadoHasta;
    }
    
    public void setLlamadoHasta(Date llamadoHasta) {
        this.llamadoHasta = llamadoHasta;
    }




}


