package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Materia generated by hbm2java
 */
public class Materia  implements java.io.Serializable {


     private Integer materiaId;
     private int planId;
     private Integer tipoMateriaId;
     private Integer materiaAno;
     private Integer materiaOrden;
     private String materiaNombre;
     private Integer materiaInscripciones;
     private Integer materiaPlanExigeFinal;
     private Integer materiaCursoIngreso;

    public Materia() {
    }

	
    public Materia(int planId) {
        this.planId = planId;
    }
    public Materia(int planId, Integer tipoMateriaId, Integer materiaAno, Integer materiaOrden, String materiaNombre, Integer materiaInscripciones, Integer materiaPlanExigeFinal, Integer materiaCursoIngreso) {
       this.planId = planId;
       this.tipoMateriaId = tipoMateriaId;
       this.materiaAno = materiaAno;
       this.materiaOrden = materiaOrden;
       this.materiaNombre = materiaNombre;
       this.materiaInscripciones = materiaInscripciones;
       this.materiaPlanExigeFinal = materiaPlanExigeFinal;
       this.materiaCursoIngreso = materiaCursoIngreso;
    }
   
    public Integer getMateriaId() {
        return this.materiaId;
    }
    
    public void setMateriaId(Integer materiaId) {
        this.materiaId = materiaId;
    }
    public int getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(int planId) {
        this.planId = planId;
    }
    public Integer getTipoMateriaId() {
        return this.tipoMateriaId;
    }
    
    public void setTipoMateriaId(Integer tipoMateriaId) {
        this.tipoMateriaId = tipoMateriaId;
    }
    public Integer getMateriaAno() {
        return this.materiaAno;
    }
    
    public void setMateriaAno(Integer materiaAno) {
        this.materiaAno = materiaAno;
    }
    public Integer getMateriaOrden() {
        return this.materiaOrden;
    }
    
    public void setMateriaOrden(Integer materiaOrden) {
        this.materiaOrden = materiaOrden;
    }
    public String getMateriaNombre() {
        return this.materiaNombre;
    }
    
    public void setMateriaNombre(String materiaNombre) {
        this.materiaNombre = materiaNombre;
    }
    public Integer getMateriaInscripciones() {
        return this.materiaInscripciones;
    }
    
    public void setMateriaInscripciones(Integer materiaInscripciones) {
        this.materiaInscripciones = materiaInscripciones;
    }
    public Integer getMateriaPlanExigeFinal() {
        return this.materiaPlanExigeFinal;
    }
    
    public void setMateriaPlanExigeFinal(Integer materiaPlanExigeFinal) {
        this.materiaPlanExigeFinal = materiaPlanExigeFinal;
    }
    public Integer getMateriaCursoIngreso() {
        return this.materiaCursoIngreso;
    }
    
    public void setMateriaCursoIngreso(Integer materiaCursoIngreso) {
        this.materiaCursoIngreso = materiaCursoIngreso;
    }




}


