package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Materiaingreso generated by hbm2java
 */
public class Materiaingreso  implements java.io.Serializable {


     private MateriaingresoId id;

    public Materiaingreso() {
    }

    public Materiaingreso(MateriaingresoId id) {
       this.id = id;
    }
   
    public MateriaingresoId getId() {
        return this.id;
    }
    
    public void setId(MateriaingresoId id) {
        this.id = id;
    }




}


