package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Nivel generated by hbm2java
 */
public class Nivel  implements java.io.Serializable {


     private Integer nivelId;
     private String nivelDescripcion;

    public Nivel() {
    }

    public Nivel(String nivelDescripcion) {
       this.nivelDescripcion = nivelDescripcion;
    }
   
    public Integer getNivelId() {
        return this.nivelId;
    }
    
    public void setNivelId(Integer nivelId) {
        this.nivelId = nivelId;
    }
    public String getNivelDescripcion() {
        return this.nivelDescripcion;
    }
    
    public void setNivelDescripcion(String nivelDescripcion) {
        this.nivelDescripcion = nivelDescripcion;
    }




}


