package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * OpcionalId generated by hbm2java
 */
public class OpcionalId  implements java.io.Serializable {


     private int materiaId;
     private Integer esOpcionalDe;

    public OpcionalId() {
    }

	
    public OpcionalId(int materiaId) {
        this.materiaId = materiaId;
    }
    public OpcionalId(int materiaId, Integer esOpcionalDe) {
       this.materiaId = materiaId;
       this.esOpcionalDe = esOpcionalDe;
    }
   
    public int getMateriaId() {
        return this.materiaId;
    }
    
    public void setMateriaId(int materiaId) {
        this.materiaId = materiaId;
    }
    public Integer getEsOpcionalDe() {
        return this.esOpcionalDe;
    }
    
    public void setEsOpcionalDe(Integer esOpcionalDe) {
        this.esOpcionalDe = esOpcionalDe;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OpcionalId) ) return false;
		 OpcionalId castOther = ( OpcionalId ) other; 
         
		 return (this.getMateriaId()==castOther.getMateriaId())
 && ( (this.getEsOpcionalDe()==castOther.getEsOpcionalDe()) || ( this.getEsOpcionalDe()!=null && castOther.getEsOpcionalDe()!=null && this.getEsOpcionalDe().equals(castOther.getEsOpcionalDe()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMateriaId();
         result = 37 * result + ( getEsOpcionalDe() == null ? 0 : this.getEsOpcionalDe().hashCode() );
         return result;
   }   


}


