package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Opcional generated by hbm2java
 */
public class Opcional  implements java.io.Serializable {


     private OpcionalId id;

    public Opcional() {
    }

    public Opcional(OpcionalId id) {
       this.id = id;
    }
   
    public OpcionalId getId() {
        return this.id;
    }
    
    public void setId(OpcionalId id) {
        this.id = id;
    }




}


