package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer paisId;
     private String paisNombre;

    public Pais() {
    }

    public Pais(String paisNombre) {
       this.paisNombre = paisNombre;
    }
   
    public Integer getPaisId() {
        return this.paisId;
    }
    
    public void setPaisId(Integer paisId) {
        this.paisId = paisId;
    }
    public String getPaisNombre() {
        return this.paisNombre;
    }
    
    public void setPaisNombre(String paisNombre) {
        this.paisNombre = paisNombre;
    }




}


