package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private Integer periodoId;
     private int cicloAno;
     private int tipoMateriaId;
     private Date periodoDesde;
     private Date periodoHasta;

    public Periodo() {
    }

	
    public Periodo(int cicloAno, int tipoMateriaId) {
        this.cicloAno = cicloAno;
        this.tipoMateriaId = tipoMateriaId;
    }
    public Periodo(int cicloAno, int tipoMateriaId, Date periodoDesde, Date periodoHasta) {
       this.cicloAno = cicloAno;
       this.tipoMateriaId = tipoMateriaId;
       this.periodoDesde = periodoDesde;
       this.periodoHasta = periodoHasta;
    }
   
    public Integer getPeriodoId() {
        return this.periodoId;
    }
    
    public void setPeriodoId(Integer periodoId) {
        this.periodoId = periodoId;
    }
    public int getCicloAno() {
        return this.cicloAno;
    }
    
    public void setCicloAno(int cicloAno) {
        this.cicloAno = cicloAno;
    }
    public int getTipoMateriaId() {
        return this.tipoMateriaId;
    }
    
    public void setTipoMateriaId(int tipoMateriaId) {
        this.tipoMateriaId = tipoMateriaId;
    }
    public Date getPeriodoDesde() {
        return this.periodoDesde;
    }
    
    public void setPeriodoDesde(Date periodoDesde) {
        this.periodoDesde = periodoDesde;
    }
    public Date getPeriodoHasta() {
        return this.periodoHasta;
    }
    
    public void setPeriodoHasta(Date periodoHasta) {
        this.periodoHasta = periodoHasta;
    }




}


