package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Planes generated by hbm2java
 */
public class Planes  implements java.io.Serializable {


     private Integer planId;
     private int carreraId;
     private String planNombre;
     private Integer planVigente;
     private Integer planActivo;
     private Date planFecha;
     private Integer planIngresoObligatorio;

    public Planes() {
    }

	
    public Planes(int carreraId) {
        this.carreraId = carreraId;
    }
    public Planes(int carreraId, String planNombre, Integer planVigente, Integer planActivo, Date planFecha, Integer planIngresoObligatorio) {
       this.carreraId = carreraId;
       this.planNombre = planNombre;
       this.planVigente = planVigente;
       this.planActivo = planActivo;
       this.planFecha = planFecha;
       this.planIngresoObligatorio = planIngresoObligatorio;
    }
   
    public Integer getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }
    public int getCarreraId() {
        return this.carreraId;
    }
    
    public void setCarreraId(int carreraId) {
        this.carreraId = carreraId;
    }
    public String getPlanNombre() {
        return this.planNombre;
    }
    
    public void setPlanNombre(String planNombre) {
        this.planNombre = planNombre;
    }
    public Integer getPlanVigente() {
        return this.planVigente;
    }
    
    public void setPlanVigente(Integer planVigente) {
        this.planVigente = planVigente;
    }
    public Integer getPlanActivo() {
        return this.planActivo;
    }
    
    public void setPlanActivo(Integer planActivo) {
        this.planActivo = planActivo;
    }
    public Date getPlanFecha() {
        return this.planFecha;
    }
    
    public void setPlanFecha(Date planFecha) {
        this.planFecha = planFecha;
    }
    public Integer getPlanIngresoObligatorio() {
        return this.planIngresoObligatorio;
    }
    
    public void setPlanIngresoObligatorio(Integer planIngresoObligatorio) {
        this.planIngresoObligatorio = planIngresoObligatorio;
    }




}


