package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1


import java.util.Date;

/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private Integer registroId;
     private Integer usuarioId;
     private Integer formularioId;
     private Integer tipoOperacionId;
     private String registroOperacion;
     private Date registroFecha;
     private Date registroHora;

    public Registro() {
    }

    public Registro(Integer usuarioId, Integer formularioId, Integer tipoOperacionId, String registroOperacion, Date registroFecha, Date registroHora) {
       this.usuarioId = usuarioId;
       this.formularioId = formularioId;
       this.tipoOperacionId = tipoOperacionId;
       this.registroOperacion = registroOperacion;
       this.registroFecha = registroFecha;
       this.registroHora = registroHora;
    }
   
    public Integer getRegistroId() {
        return this.registroId;
    }
    
    public void setRegistroId(Integer registroId) {
        this.registroId = registroId;
    }
    public Integer getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }
    public Integer getFormularioId() {
        return this.formularioId;
    }
    
    public void setFormularioId(Integer formularioId) {
        this.formularioId = formularioId;
    }
    public Integer getTipoOperacionId() {
        return this.tipoOperacionId;
    }
    
    public void setTipoOperacionId(Integer tipoOperacionId) {
        this.tipoOperacionId = tipoOperacionId;
    }
    public String getRegistroOperacion() {
        return this.registroOperacion;
    }
    
    public void setRegistroOperacion(String registroOperacion) {
        this.registroOperacion = registroOperacion;
    }
    public Date getRegistroFecha() {
        return this.registroFecha;
    }
    
    public void setRegistroFecha(Date registroFecha) {
        this.registroFecha = registroFecha;
    }
    public Date getRegistroHora() {
        return this.registroHora;
    }
    
    public void setRegistroHora(Date registroHora) {
        this.registroHora = registroHora;
    }




}


