package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * RequisitocicloId generated by hbm2java
 */
public class RequisitocicloId  implements java.io.Serializable {


     private int requisitoId;
     private int cicloAno;

    public RequisitocicloId() {
    }

    public RequisitocicloId(int requisitoId, int cicloAno) {
       this.requisitoId = requisitoId;
       this.cicloAno = cicloAno;
    }
   
    public int getRequisitoId() {
        return this.requisitoId;
    }
    
    public void setRequisitoId(int requisitoId) {
        this.requisitoId = requisitoId;
    }
    public int getCicloAno() {
        return this.cicloAno;
    }
    
    public void setCicloAno(int cicloAno) {
        this.cicloAno = cicloAno;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RequisitocicloId) ) return false;
		 RequisitocicloId castOther = ( RequisitocicloId ) other; 
         
		 return (this.getRequisitoId()==castOther.getRequisitoId())
 && (this.getCicloAno()==castOther.getCicloAno());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRequisitoId();
         result = 37 * result + this.getCicloAno();
         return result;
   }   


}


