package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * RequisitoalumnoId generated by hbm2java
 */
public class RequisitoalumnoId  implements java.io.Serializable {


     private int requisitoId;
     private int alumnoId;

    public RequisitoalumnoId() {
    }

    public RequisitoalumnoId(int requisitoId, int alumnoId) {
       this.requisitoId = requisitoId;
       this.alumnoId = alumnoId;
    }
   
    public int getRequisitoId() {
        return this.requisitoId;
    }
    
    public void setRequisitoId(int requisitoId) {
        this.requisitoId = requisitoId;
    }
    public int getAlumnoId() {
        return this.alumnoId;
    }
    
    public void setAlumnoId(int alumnoId) {
        this.alumnoId = alumnoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RequisitoalumnoId) ) return false;
		 RequisitoalumnoId castOther = ( RequisitoalumnoId ) other; 
         
		 return (this.getRequisitoId()==castOther.getRequisitoId())
 && (this.getAlumnoId()==castOther.getAlumnoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getRequisitoId();
         result = 37 * result + this.getAlumnoId();
         return result;
   }   


}


