package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Requisito generated by hbm2java
 */
public class Requisito  implements java.io.Serializable {


     private Integer requisitoId;
     private String requisitoDescripcion;

    public Requisito() {
    }

    public Requisito(String requisitoDescripcion) {
       this.requisitoDescripcion = requisitoDescripcion;
    }
   
    public Integer getRequisitoId() {
        return this.requisitoId;
    }
    
    public void setRequisitoId(Integer requisitoId) {
        this.requisitoId = requisitoId;
    }
    public String getRequisitoDescripcion() {
        return this.requisitoDescripcion;
    }
    
    public void setRequisitoDescripcion(String requisitoDescripcion) {
        this.requisitoDescripcion = requisitoDescripcion;
    }




}


