package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Requisitociclo generated by hbm2java
 */
public class Requisitociclo  implements java.io.Serializable {


     private RequisitocicloId id;
     private Integer requisitoCicloObligatorio;

    public Requisitociclo() {
    }

	
    public Requisitociclo(RequisitocicloId id) {
        this.id = id;
    }
    public Requisitociclo(RequisitocicloId id, Integer requisitoCicloObligatorio) {
       this.id = id;
       this.requisitoCicloObligatorio = requisitoCicloObligatorio;
    }
   
    public RequisitocicloId getId() {
        return this.id;
    }
    
    public void setId(RequisitocicloId id) {
        this.id = id;
    }
    public Integer getRequisitoCicloObligatorio() {
        return this.requisitoCicloObligatorio;
    }
    
    public void setRequisitoCicloObligatorio(Integer requisitoCicloObligatorio) {
        this.requisitoCicloObligatorio = requisitoCicloObligatorio;
    }




}


