package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Tipoinscripcion generated by hbm2java
 */
public class Tipoinscripcion  implements java.io.Serializable {


     private Integer tipoInscripcionId;
     private String tipoInscripcionDescripcion;
     private Integer tipoInscripcionUnoEnCiclo;

    public Tipoinscripcion() {
    }

    public Tipoinscripcion(String tipoInscripcionDescripcion, Integer tipoInscripcionUnoEnCiclo) {
       this.tipoInscripcionDescripcion = tipoInscripcionDescripcion;
       this.tipoInscripcionUnoEnCiclo = tipoInscripcionUnoEnCiclo;
    }
   
    public Integer getTipoInscripcionId() {
        return this.tipoInscripcionId;
    }
    
    public void setTipoInscripcionId(Integer tipoInscripcionId) {
        this.tipoInscripcionId = tipoInscripcionId;
    }
    public String getTipoInscripcionDescripcion() {
        return this.tipoInscripcionDescripcion;
    }
    
    public void setTipoInscripcionDescripcion(String tipoInscripcionDescripcion) {
        this.tipoInscripcionDescripcion = tipoInscripcionDescripcion;
    }
    public Integer getTipoInscripcionUnoEnCiclo() {
        return this.tipoInscripcionUnoEnCiclo;
    }
    
    public void setTipoInscripcionUnoEnCiclo(Integer tipoInscripcionUnoEnCiclo) {
        this.tipoInscripcionUnoEnCiclo = tipoInscripcionUnoEnCiclo;
    }




}


