package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Tipooperacion generated by hbm2java
 */
public class Tipooperacion  implements java.io.Serializable {


     private Integer tipoOperacionId;
     private String tipoOperacionNombre;

    public Tipooperacion() {
    }

    public Tipooperacion(String tipoOperacionNombre) {
       this.tipoOperacionNombre = tipoOperacionNombre;
    }
   
    public Integer getTipoOperacionId() {
        return this.tipoOperacionId;
    }
    
    public void setTipoOperacionId(Integer tipoOperacionId) {
        this.tipoOperacionId = tipoOperacionId;
    }
    public String getTipoOperacionNombre() {
        return this.tipoOperacionNombre;
    }
    
    public void setTipoOperacionNombre(String tipoOperacionNombre) {
        this.tipoOperacionNombre = tipoOperacionNombre;
    }




}


