package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Tipomateria generated by hbm2java
 */
public class Tipomateria  implements java.io.Serializable {


     private Integer tipoMateriaId;
     private String tipoMateriaDescripcion;
     private Integer tipoMateriaSemanas;

    public Tipomateria() {
    }

    public Tipomateria(String tipoMateriaDescripcion, Integer tipoMateriaSemanas) {
       this.tipoMateriaDescripcion = tipoMateriaDescripcion;
       this.tipoMateriaSemanas = tipoMateriaSemanas;
    }
   
    public Integer getTipoMateriaId() {
        return this.tipoMateriaId;
    }
    
    public void setTipoMateriaId(Integer tipoMateriaId) {
        this.tipoMateriaId = tipoMateriaId;
    }
    public String getTipoMateriaDescripcion() {
        return this.tipoMateriaDescripcion;
    }
    
    public void setTipoMateriaDescripcion(String tipoMateriaDescripcion) {
        this.tipoMateriaDescripcion = tipoMateriaDescripcion;
    }
    public Integer getTipoMateriaSemanas() {
        return this.tipoMateriaSemanas;
    }
    
    public void setTipoMateriaSemanas(Integer tipoMateriaSemanas) {
        this.tipoMateriaSemanas = tipoMateriaSemanas;
    }




}


