package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Tipodocumento generated by hbm2java
 */
public class Tipodocumento  implements java.io.Serializable {


     private Integer tipoDocumentoId;
     private String tipoDocumentoNombre;
     private String tipoDocumentoAbreviado;

    public Tipodocumento() {
    }

    public Tipodocumento(String tipoDocumentoNombre, String tipoDocumentoAbreviado) {
       this.tipoDocumentoNombre = tipoDocumentoNombre;
       this.tipoDocumentoAbreviado = tipoDocumentoAbreviado;
    }
   
    public Integer getTipoDocumentoId() {
        return this.tipoDocumentoId;
    }
    
    public void setTipoDocumentoId(Integer tipoDocumentoId) {
        this.tipoDocumentoId = tipoDocumentoId;
    }
    public String getTipoDocumentoNombre() {
        return this.tipoDocumentoNombre;
    }
    
    public void setTipoDocumentoNombre(String tipoDocumentoNombre) {
        this.tipoDocumentoNombre = tipoDocumentoNombre;
    }
    public String getTipoDocumentoAbreviado() {
        return this.tipoDocumentoAbreviado;
    }
    
    public void setTipoDocumentoAbreviado(String tipoDocumentoAbreviado) {
        this.tipoDocumentoAbreviado = tipoDocumentoAbreviado;
    }




}


