package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Titulo generated by hbm2java
 */
public class Titulo  implements java.io.Serializable {


     private Integer tituloId;
     private String tituloNombre;

    public Titulo() {
    }

    public Titulo(String tituloNombre) {
       this.tituloNombre = tituloNombre;
    }
   
    public Integer getTituloId() {
        return this.tituloId;
    }
    
    public void setTituloId(Integer tituloId) {
        this.tituloId = tituloId;
    }
    public String getTituloNombre() {
        return this.tituloNombre;
    }
    
    public void setTituloNombre(String tituloNombre) {
        this.tituloNombre = tituloNombre;
    }




}


