package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Tmp generated by hbm2java
 */
public class Tmp  implements java.io.Serializable {


     private Integer tmp;

    public Tmp() {
    }

    public Tmp(Integer tmp) {
       this.tmp = tmp;
    }
   
    public Integer getTmp() {
        return this.tmp;
    }
    
    public void setTmp(Integer tmp) {
        this.tmp = tmp;
    }




}


