package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Turnonombre generated by hbm2java
 */
public class Turnonombre  implements java.io.Serializable {


     private Integer turnoNombreId;
     private String turnoNombreDescripcion;
     private Integer turnoNombreLlamados;

    public Turnonombre() {
    }

    public Turnonombre(String turnoNombreDescripcion, Integer turnoNombreLlamados) {
       this.turnoNombreDescripcion = turnoNombreDescripcion;
       this.turnoNombreLlamados = turnoNombreLlamados;
    }
   
    public Integer getTurnoNombreId() {
        return this.turnoNombreId;
    }
    
    public void setTurnoNombreId(Integer turnoNombreId) {
        this.turnoNombreId = turnoNombreId;
    }
    public String getTurnoNombreDescripcion() {
        return this.turnoNombreDescripcion;
    }
    
    public void setTurnoNombreDescripcion(String turnoNombreDescripcion) {
        this.turnoNombreDescripcion = turnoNombreDescripcion;
    }
    public Integer getTurnoNombreLlamados() {
        return this.turnoNombreLlamados;
    }
    
    public void setTurnoNombreLlamados(Integer turnoNombreLlamados) {
        this.turnoNombreLlamados = turnoNombreLlamados;
    }




}


