package ar.pauen.modelo;
// Generated 21/02/2012 14:25:42 by Hibernate Tools 3.4.0.CR1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer usuarioId;
     private String usuarioNombre;
     private String usuarioPassword;
     private String usuarioDescripcion;
     private byte[] usuarioObservaciones;
     private Integer usuarioAdministrador;

    public Usuario() {
    }

	
    public Usuario(byte[] usuarioObservaciones) {
        this.usuarioObservaciones = usuarioObservaciones;
    }
    public Usuario(String usuarioNombre, String usuarioPassword, String usuarioDescripcion, byte[] usuarioObservaciones, Integer usuarioAdministrador) {
       this.usuarioNombre = usuarioNombre;
       this.usuarioPassword = usuarioPassword;
       this.usuarioDescripcion = usuarioDescripcion;
       this.usuarioObservaciones = usuarioObservaciones;
       this.usuarioAdministrador = usuarioAdministrador;
    }
   
    public Integer getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(Integer usuarioId) {
        this.usuarioId = usuarioId;
    }
    public String getUsuarioNombre() {
        return this.usuarioNombre;
    }
    
    public void setUsuarioNombre(String usuarioNombre) {
        this.usuarioNombre = usuarioNombre;
    }
    public String getUsuarioPassword() {
        return this.usuarioPassword;
    }
    
    public void setUsuarioPassword(String usuarioPassword) {
        this.usuarioPassword = usuarioPassword;
    }
    public String getUsuarioDescripcion() {
        return this.usuarioDescripcion;
    }
    
    public void setUsuarioDescripcion(String usuarioDescripcion) {
        this.usuarioDescripcion = usuarioDescripcion;
    }
    public byte[] getUsuarioObservaciones() {
        return this.usuarioObservaciones;
    }
    
    public void setUsuarioObservaciones(byte[] usuarioObservaciones) {
        this.usuarioObservaciones = usuarioObservaciones;
    }
    public Integer getUsuarioAdministrador() {
        return this.usuarioAdministrador;
    }
    
    public void setUsuarioAdministrador(Integer usuarioAdministrador) {
        this.usuarioAdministrador = usuarioAdministrador;
    }




}


